### ISSUE TITLE
Execution not working if sandbox.type === "none"

### ISSUE THREAD

**Issue by ilAYAli** [mattgodbolt/compiler-explorer#1023]
OS: macOS
HEAD: be4ac50e6b88d4eab9f8c2252a0c7e3301225974

It seems that local execution is no longer working.
This might be related to not using Docker for sandboxing?

```
Internal Compiler Explorer error: TypeError: Cannot read property 'on' of undefined
    at setupOnError (/Users/petter/source/compiler-explorer/lib/exec.js:76:16)
    at execute (/Users/petter/source/compiler-explorer/lib/exec.js:97:5)
    at Object.sandbox (/Users/petter/source/compiler-explorer/lib/exec.js:133:16)
    at DefaultCompiler.execBinary (/Users/petter/source/compiler-explorer/lib/base-compiler.js:134:21)
    at DefaultCompiler.postProcess (/Users/petter/source/compiler-explorer/lib/base-compiler.js:579:32)
    at stat.then.catch.then (/Users/petter/source/compiler-explorer/lib/base-compiler.js:233:30)
Compiler returned: -1
```

Here is the commit I use to enable local execution on macOS:
```
From 936b71aed9950af2fe41112980a6c410d54e0685 Mon Sep 17 00:00:00 2001
From: Petter Wahlman <pwahlman@cisco.com>
Date: Wed, 20 Jun 2018 07:39:23 +0200
Subject: [PATCH] config

---
 etc/config/c++.defaults.properties | 7 ++++---
 etc/config/llvm.default.properties | 8 ++++----
 2 files changed, 8 insertions(+), 7 deletions(-)

diff --git a/etc/config/c++.defaults.properties b/etc/config/c++.defaults.properties
index a64a8124..0d06c008 100644
--- a/etc/config/c++.defaults.properties
+++ b/etc/config/c++.defaults.properties
@@ -1,11 +1,12 @@
 # Default settings for C++
 # AP: Add &cl group
-compilers=/usr/bin/g++-4.4:/usr/bin/g++-4.5:/usr/bin/g++-4.6:/usr/bin/g++-4.7:/usr/bin/g++-4.8:/usr/bin/clang++:/usr/bin/g++-5:/usr/bin/g++-7:/usr/bin/g++-6:/usr/bin/g++:&cl
-defaultCompiler=/usr/bin/g++
+compilers=/Users/petter/local/bin/clang++:/usr/bin/clang++:&cl
+defaultCompiler=/Users/petter/local/bin/clang++
 postProcess=
 demangler=c++filt
 demanglerClassFile=./demangler-cpp
-objdumper=objdump
+objdumper=gobjdump
+supportsExecute=true
 #androidNdk=/opt/google/android-ndk-r9c
 options=
 supportsBinary=true
diff --git a/etc/config/llvm.default.properties b/etc/config/llvm.default.properties
index d2017f1e..1d56010e 100644
--- a/etc/config/llvm.default.properties
+++ b/etc/config/llvm.default.properties
@@ -8,11 +8,11 @@ defaultCompiler=irclang
 compiler.irclang.intelAsm=-masm=intel
 compiler.irclang.groupName=Clang x86-64
 compiler.irclang.options=-x ir
-compiler.irclang.exe=/usr/bin/clang++
-compiler.irclang.name=clang 3.9.1
+compiler.irclang.exe=/Users/petter/local/bin/clang++
+compiler.irclang.name=clang 7.0.0

 compiler.llc.compilerType=llc
-compiler.llc.supportsExecute=false
+compiler.llc.supportsExecute=true
 compiler.llc.intelAsm=-masm=intel
 compiler.llc.groupName=LLVM Static Compiler
 compiler.llc.versionRe=LLVM version .*
@@ -21,7 +21,7 @@ compiler.llc.name=llc

 compiler.opt.compilerType=opt
 compiler.opt.supportsBinary=false
-compiler.opt.supportsExecute=false
+compiler.opt.supportsExecute=true
 compiler.opt.groupName=LLVM optimizer
 compiler.opt.versionRe=LLVM version .*
 compiler.opt.exe=/usr/bin/pot
--
2.16.1
```

make output:
```
Haskell language support disabled
D language support disabled
Rust language support disabled
/Users/petter/source/compiler-explorer/node_modules/.bin/yarn install
yarn install v1.9.2
[1/5] 🔍  Validating package.json...
[2/5] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.49s.
/usr/local/bin/node node_modules/webpack/bin/webpack.js
Child
    Hash: fe660cea4351b37cd6dd
    Version: webpack 3.10.0
    Time: 893ms
                                                            Asset       Size  Chunks             Chunk Names
                                          .site-logo.svg.ignoreme    2.59 kB       0  [emitted]  site-logo.svg
            GitHub-Mark-20px.5baab2d4072294ab236e0886ba739273.png  658 bytes          [emitted]
                patreon_logo.b3992c62cc04cc8edb3e513a6da84cb3.png  987 bytes          [emitted]
                 Reddit_Icon.45e0b943431ea4a17fe87069cebbad57.png  460 bytes          [emitted]
              site-logo-beta.155884bf9fbddf60d80ee9e4740609eb.svg    6.15 kB          [emitted]
           site-logo-inverse.40cafd660c406e77e4971bfb68196684.svg    10.3 kB          [emitted]
                   site-logo.3f5bcf90b56ade7be40ffa8cca8b2056.svg    10.1 kB          [emitted]
    Twitter_Logo_WhiteOnBlue.d00ce21957e1bc4c45f9e3ca57c14826.svg  914 bytes          [emitted]
          Google-Groups-20px.68f30c7dbd8e0235cf1c52bb2ae11736.png    1.18 kB          [emitted]
                                  .site-logo-inverse.svg.ignoreme     2.6 kB       1  [emitted]  site-logo-inverse.svg
                                     .site-logo-beta.svg.ignoreme    2.59 kB       2  [emitted]  site-logo-beta.svg
                                       .patreon_logo.png.ignoreme    2.59 kB       3  [emitted]  patreon_logo.png
                           .Twitter_Logo_WhiteOnBlue.svg.ignoreme     2.6 kB       4  [emitted]  Twitter_Logo_WhiteOnBlue.svg
                                        .Reddit_Icon.png.ignoreme    2.59 kB       5  [emitted]  Reddit_Icon.png
                                 .Google-Groups-20px.png.ignoreme     2.6 kB       6  [emitted]  Google-Groups-20px.png
                                   .GitHub-Mark-20px.png.ignoreme    2.59 kB       7  [emitted]  GitHub-Mark-20px.png
                                                    manifest.json    1.19 kB          [emitted]
       [0] ./static/assets/GitHub-Mark-20px.png 99 bytes {7} [built]
       [1] ./static/assets/Google-Groups-20px.png 101 bytes {6} [built]
       [2] ./static/assets/patreon_logo.png 95 bytes {3} [built]
       [3] ./static/assets/Reddit_Icon.png 94 bytes {5} [built]
       [4] ./static/assets/site-logo-beta.svg 97 bytes {2} [built]
       [5] ./static/assets/site-logo-inverse.svg 100 bytes {1} [built]
       [6] ./static/assets/site-logo.svg 92 bytes {0} [built]
       [7] ./static/assets/Twitter_Logo_WhiteOnBlue.svg 107 bytes {4} [built]
/Library/Developer/CommandLineTools/usr/bin/make -C c-preload
make[1]: Nothing to be done for `all'.
/usr/local/bin/node ./node_modules/.bin/supervisor -w app.js,lib,etc/config -e 'js|node|properties' --exec /usr/local/bin/node  -- ./app.js

Running node-supervisor with
  program './app.js'
  --watch 'app.js,lib,etc/config'
  --extensions 'js|node|properties'
  --exec '/usr/local/bin/node'

Starting child process with '/usr/local/bin/node ./app.js'
Watching directory '/Users/petter/source/compiler-explorer/app.js' for changes.
Press rs for restarting the process.
Watching directory '/Users/petter/source/compiler-explorer/lib' for changes.
Press rs for restarting the process.
Watching directory '/Users/petter/source/compiler-explorer/etc/config' for changes.
Press rs for restarting the process.
info: properties hierarchy: defaults, dev, dev.darwin, darwin, pwa-mbp.local, local
info: Reading properties from ./etc/config with hierarchy defaults,dev,dev.darwin,darwin,pwa-mbp.local,local
info: Created cache of type InMemoryCache(50Mb)
clang: error: unknown argument: '-print-multiarch'
clang: error: no input files
warn: Unable to get multiarch: Error: Command failed: gcc -print-multiarch
clang: error: unknown argument: '-print-multiarch'
clang: error: no input files

info: Cleaning temp dirs every 600 secs
info: Exes found: c++=[/Users/petter/local/bin/clang++, /usr/bin/clang++, &cl], llvm=[], cppx=[], c=[/usr/bin/gcc-4.4, /usr/bin/gcc-4.5, /usr/bin/gcc-4.6, /usr/bin/gcc-4.7, /usr/bin/gcc-4.8, /usr/bin/clangcc, /usr/bin/gcc-5, /usr/bin/gcc-7, /usr/bin/gcc-6, /usr/bin/gcc], rust=[/usr/local/bin/rustc], d=[/usr/bin/gdc, /usr/bin/gdc-4.4, /usr/bin/gdc-4.6], go=[], ispc=[], haskell=[/usr/bin/ghc], swift=[], pascal=[/usr/bin/fpc], assembly=[&nasm, &gnuas], analysis=[&llvm-mca], cuda=[&nvcc, &clang]
info: Loading compiler from ../compilers/default
info: Loading compiler from ../compilers/WSL-CL
info: Loading compiler from ../compilers/rust
info: Loading compiler from ../compilers/haskell
info: Loading compiler from ../compilers/pascal
info: Loading compiler from ../compilers/assembly
info: Loading compiler from ../compilers/llvm-mca
info: Loading compiler from ../compilers/nvcc
info: Gathering /Users/petter/local/bin/clang++ version information on /Users/petter/local/bin/clang++
info: Gathering /usr/bin/clang++ version information on /usr/bin/clang++
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/gcc-4.4'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/mnt/c/str/windows/19.10.25017/lib/native/bin/amd64/cl.exe'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/gcc-4.6'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/gcc-4.5'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/gcc-4.7'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/gcc-4.8'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/clangcc'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/gcc-5'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/gcc-7'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/gcc-6'
info: Gathering /usr/bin/gcc version information on /usr/bin/gcc
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/local/bin/rustc'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/gdc'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/gdc-4.4'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/gdc-4.6'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/ghc'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/fpc'
info: Gathering defaultnasm version information on /usr/bin/nasm
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/usr/bin/llvm-mca'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/opt/compiler-explorer/cuda/9.1.85/bin/nvcc'
warn: Unable to stat compiler binary Error: ENOENT: no such file or directory, stat '/opt/compiler-explorer/clang-trunk/bin/clang++'
info: Gathering defaultgnuas version information on /usr/bin/as
raven@2.3.0 alert: no DSN provided, error reporting disabled
info: =======================================
info:   git release 936b71aed9950af2fe41112980a6c410d54e0685
info:   serving static files from 'static'
info:   Listening on http://localhost:10240/
info: =======================================
```

**Comment by partouf** [comment]
This error is mostly from not being able to execute the executable, because it's probably not there.

The compilation doesn't actually generate the executable if you don't enable on the IOIOIO option. (which in turn causes an objdump error, but the execution will still occur)

**Comment by ilAYAli** [comment]
non-sandboxed execution has previously worked for me:
https://github.com/mattgodbolt/compiler-explorer/issues/429#issuecomment-313858556

**Comment by RabsRincon** [comment]
Hi @ilAYAli. This is error is somewhat puzzling. 

Could you try running `make EXTRA_ARGS="--debug"` to see if we can see something in the whole log which stands out?

**Comment by ilAYAli** [comment]
Hi!
Sorry for the delay. Attached is the output from `make clean;make EXTRA_ARGS="--debug"`

[make-output.txt](https://github.com/mattgodbolt/compiler-explorer/files/2256381/make-output.txt)

**Comment by mattgodbolt** [comment]
HI @ilAYAli - thanks! We need to see the result of you trying to execute something in the debug: can you run `make EXTRA_ARGS="--debug"` and then hit localhost:10240 and try executing a simple program?

Please attach the output after the `Listening on http://localhost:10240/` line (we have the information we need from above that).

Thanks!

**Comment by ilAYAli** [comment]
Hi Matt!

code:
```
#include <cstdio>
int main()
{
    puts("foo");
}
```

log:
```
info: =======================================
info:   git release b77f211f9809f1d32c064dad33b6a91fd6f9c655
info:   serving static files from 'static'
info:   Listening on http://localhost:10240/
info: =======================================
debug:  type=executing, command=/usr/bin/clang++, args=[-g, -o, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-1c9y1ja.v30k/output.s, -fcolor-diagnostics, -std=c++17, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-1c9y1ja.v30k/example.cpp]
debug:  type=exited, code=0
debug:  type=executed, command=/usr/bin/clang++, args=[-g, -o, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-1c9y1ja.v30k/output.s, -fcolor-diagnostics, -std=c++17, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-1c9y1ja.v30k/example.cpp], code=0, stdout=, stderr=, okToCache=true
debug:  type=executing, command=gobjdump, args=[-d, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-1c9y1ja.v30k/output.s, -l, --insn-width=16, -C, -M, intel]
debug:  type=exited, code=1
debug:  type=executed, command=gobjdump, args=[-d, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-1c9y1ja.v30k/output.s, -l, --insn-width=16, -C, -M, intel], code=1, stdout=, stderr=gobjdump: /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-1c9y1ja.v30k/output.s: unknown load command 0x32
gobjdump: /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-1c9y1ja.v30k/output.s: unknown load command 0x32
gobjdump: /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-1c9y1ja.v30k/output.s: unknown load command 0x32
gobjdump: /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-1c9y1ja.v30k/output.s: file format not recognized
, okToCache=true
debug:  type=executing, command=c++filt, args=[]
debug:  type=exited, code=0
debug:  type=executed, command=c++filt, args=[], code=0, stdout=returned, stderr=, okToCache=true
(node:41706) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
info: ::1 "POST /api/compiler/%2Fusr%2Fbin%2Fclang%2B%2B/compile" 200
debug:  type=executing, command=/usr/bin/clang++, args=[-g, -o, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-xaddgh.fwn2n/output.s, -S, -fcolor-diagnostics, -std=c++17, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-xaddgh.fwn2n/example.cpp]
debug:  type=exited, code=0
debug:  type=executed, command=/usr/bin/clang++, args=[-g, -o, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-xaddgh.fwn2n/output.s, -S, -fcolor-diagnostics, -std=c++17, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-41706-xaddgh.fwn2n/example.cpp], code=0, stdout=, stderr=, okToCache=true
debug:  type=executing, command=c++filt, args=[]
debug:  type=exited, code=0
debug:  type=executed, command=c++filt, args=[], code=0, stdout=L_.str
_main
_puts, stderr=, okToCache=true
info: ::1 "POST /api/compiler/%2Fusr%2Fbin%2Fclang%2B%2B/compile" 200
```

**Comment by mattgodbolt** [comment]
Hmm; I don't see it trying to execute at all there! You definitely had the `a.out` button ticked to execute?

Can you open up your Javascript console (ctrl-shift-J in Chrome, similar in other browsers); then re-execute and paste anything you see there? It's possible the error is in the JS code before it even gets to the server.

**Comment by ilAYAli** [comment]
<img width="862" alt="screenshot 2018-08-03 at 14 18 21" src="https://user-images.githubusercontent.com/1106732/43642500-1be251e8-9728-11e8-8082-8886ce19475f.png">

Safari developer console:
```
[Error] Refused to load blob:http://localhost:10240/db4f87f7-fb2d-4ccc-9b64-33e24ab76def because it does not appear in the script-src directive of the Content Security Policy.
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (loader.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (editor.main.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (editor.main.nls.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (workerMain.js.map, line 0)
```

**Comment by mattgodbolt** [comment]
Ah...try ticking the `11010` box as well as the `./a.out`

**Comment by ilAYAli** [comment]
Still no execution output:

<img width="1920" alt="screenshot 2018-08-03 at 14 30 31" src="https://user-images.githubusercontent.com/1106732/43642967-d49a0086-9729-11e8-85d3-79fa5e74cfb1.png">



Javascript console:
```
[Error] Refused to load blob:http://localhost:10240/d1d0b670-c5dd-454d-9bd2-8ed7ad19a371 because it does not appear in the script-src directive of the Content Security Policy.
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (loader.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (editor.main.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (editor.main.nls.js.map, line 0)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (workerMain.js.map, line 0)
```

**Comment by mattgodbolt** [comment]
Anything in the debug output in the shell?

**Comment by ilAYAli** [comment]
```
info: ::1 "POST /api/compiler/%2Fusr%2Fbin%2Fclang%2B%2B/compile" 200
debug:  type=executing, command=/usr/bin/clang++, args=[-g, -o, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-9bgemp.xnrna/output.s, -fcolor-diagnostics, -std=c++14, /var/folders/3p/80s_1kbd37lch5c
ryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-9bgemp.xnrna/example.cpp]
debug:  type=exited, code=0
debug:  type=executed, command=/usr/bin/clang++, args=[-g, -o, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-9bgemp.xnrna/output.s, -fcolor-diagnostics, -std=c++14, /var/folders/3p/80s_1kbd37lch5cr
yfv61_m00000gn/T/compiler-explorer-compiler11873-42086-9bgemp.xnrna/example.cpp], code=0, stdout=, stderr=, okToCache=true
debug:  type=executing, command=gobjdump, args=[-d, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-9bgemp.xnrna/output.s, -l, --insn-width=16, -C, -M, intel]
debug:  type=exited, code=1
debug:  type=executed, command=gobjdump, args=[-d, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-9bgemp.xnrna/output.s, -l, --insn-width=16, -C, -M, intel], code=1, stdout=, stderr=gobjdump: /var/f
olders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-9bgemp.xnrna/output.s: unknown load command 0x32
gobjdump: /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-9bgemp.xnrna/output.s: unknown load command 0x32
gobjdump: /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-9bgemp.xnrna/output.s: unknown load command 0x32
gobjdump: /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-9bgemp.xnrna/output.s: file format not recognized
, okToCache=true
debug:  type=executing, command=c++filt, args=[]
debug:  type=exited, code=0
debug:  type=executed, command=c++filt, args=[], code=0, stdout=returned, stderr=, okToCache=true
info: ::1 "POST /api/compiler/%2Fusr%2Fbin%2Fclang%2B%2B/compile" 200
debug:  type=executing, command=/usr/bin/clang++, args=[-g, -o, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-i004qc.mwz0a/output.s, -S, -fcolor-diagnostics, -std=c++14, /var/folders/3p/80s_1kbd37l
ch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-i004qc.mwz0a/example.cpp]
debug:  type=exited, code=0
debug:  type=executed, command=/usr/bin/clang++, args=[-g, -o, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-i004qc.mwz0a/output.s, -S, -fcolor-diagnostics, -std=c++14, /var/folders/3p/80s_1kbd37lc
h5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-i004qc.mwz0a/example.cpp], code=0, stdout=, stderr=, okToCache=true
debug:  type=executing, command=c++filt, args=[]
debug:  type=exited, code=0
debug:  type=executed, command=c++filt, args=[], code=0, stdout=L_.str
_main
_puts, stderr=, okToCache=true
info: ::1 "POST /api/compiler/%2Fusr%2Fbin%2Fclang%2B%2B/compile" 200
info: ::1 "GET /api/asm/movq" 200
info: ::1 "GET /api/asm/retq" 200
info: ::1 "GET /" 200
info: ::1 "GET /" 304
info: ::1 "GET /" 200
warn: ::1 "GET /min-maps/vs/loader.js.map" 404
warn: ::1 "GET /min-maps/vs/editor/editor.main.js.map" 404
info: ::1 "GET /source/builtin/list" 200
info: ::1 "POST /api/compiler/%2Fusr%2Fbin%2Fclang%2B%2B/compile" 200
warn: ::1 "GET /min-maps/vs/editor/editor.main.nls.js.map" 404
warn: ::1 "GET /min-maps/vs/base/worker/workerMain.js.map" 404
info: ::1 "GET /api/asm/leaq" 200
info: ::1 "POST /api/compiler/%2Fusr%2Fbin%2Fclang%2B%2B/compile" 200
debug:  type=executing, command=/usr/bin/clang++, args=[-g, -o, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-sm4m1h.dgbcr/output.s, -S, -fcolor-diagnostics, -std=c++14, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-sm4m1h.dgbcr/example.cpp]
debug:  type=exited, code=0
debug:  type=executed, command=/usr/bin/clang++, args=[-g, -o, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-sm4m1h.dgbcr/output.s, -S, -fcolor-diagnostics, -std=c++14, /var/folders/3p/80s_1kbd37lch5cryfv61_m00000gn/T/compiler-explorer-compiler11873-42086-sm4m1h.dgbcr/example.cpp], code=0, stdout=, stderr=, okToCache=true
debug:  type=executing, command=c++filt, args=[]
debug:  type=exited, code=0
```

**Comment by mattgodbolt** [comment]
Thanks...we will have to have a think what's going on here!

**Comment by mattgodbolt** [comment]
compiler-explorer-compiler11873-42086-9bgemp.xnrna/output.s: file format not recognized

**Comment by mattgodbolt** [comment]
This seems to be the trouble. The compiled program (which is poorly named as XXX.s even though it should be an executable..) is not actually an executable

**Comment by mattgodbolt** [comment]
I am at work now, but hoping someone else can spot the problem, else I'll.look later on. Thanks again

**Comment by mattgodbolt** [comment]
Hmm I'm even less sure now what's going on, now at a computer and wondering what's going on. I have a Mac laptop at work and I'll try running it on that next week, and see if I can debug something.

If you're feeling brave you could litter the code with "console.log" or logger.info() calls around the `postProcess` code: https://github.com/mattgodbolt/compiler-explorer/blob/master/lib/base-compiler.js#L547 and see if you can troubleshoot from that!

**Comment by RabsRincon** [comment]
Hi @ilAYAli Apologies about this issue not getting any attention for so long. Could you try to reproduce your problem now? @mattgodbolt has been hard at work adding execution support to the site and your issue might have unintentionally been fixed :)

**Comment by ilAYAli** [comment]
It seems much has improved since my initial feedback.
The only thing that I had to do to make local execution work on macOS Mojave was:
`brew install binutils` and replace `objdump` in `etc/config/c++.defaults.properties` with the absolute of the binutils provided objdump: `/usr/local/Cellar/binutils/2.32/bin/objdump`
Good job!
