### ISSUE TITLE
node exits with corrupt JSON

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1167]
Seeing this kind of thing in the logs:

```
Nov 12 12:06:21 35c559e8ede9 unified:  SyntaxError: Unexpected token < in JSON at position 0 
Nov 12 12:06:21 35c559e8ede9 unified:      at JSON.parse (<anonymous>) 
Nov 12 12:06:21 35c559e8ede9 unified:      at IncomingMessage.res.on (/compiler-explorer/lib/compiler-finder.js:77:46) 
Nov 12 12:06:21 35c559e8ede9 unified:      at emitNone (events.js:111:20) 
Nov 12 12:06:21 35c559e8ede9 unified:      at IncomingMessage.emit (events.js:208:7) 
Nov 12 12:06:21 35c559e8ede9 unified:      at endReadableNT (_stream_readable.js:1055:12) 
Nov 12 12:06:21 35c559e8ede9 unified:      at _combinedTickCallback (internal/process/next_tick.js:138:11) 
Nov 12 12:06:21 35c559e8ede9 unified:      at process._tickDomainCallback (internal/process/next_tick.js:218:9) 
Nov 12 12:06:21 35c559e8ede9 unified:  Mon Nov 12 2018 18:06:21 GMT+0000 (UTC) 
```

My suspicion is some kind of error from the downstream Microsoft compiler site, maybe returning a non-JSON reply (`<html> error` type thing maybe?). Either way we shouldn't crash out.

**Comment by mattgodbolt** [comment]
During startup we see similar issues:

```
Nov 12 15:00:04 ip-172-30-5-251 compiler-explorer:  undefined:1
Nov 12 15:00:04 ip-172-30-5-251 compiler-explorer:  <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
Nov 12 15:00:04 ip-172-30-5-251 compiler-explorer:  ^
Nov 12 15:00:04 ip-172-30-5-251 compiler-explorer:  SyntaxError: Unexpected token < in JSON at position 0
Nov 12 15:00:04 ip-172-30-5-251 compiler-explorer:      at JSON.parse (<anonymous>)
Nov 12 15:00:04 ip-172-30-5-251 compiler-explorer:      at IncomingMessage.res.on (/compiler-explorer/lib/compiler-finder.js:77:46)
Nov 12 15:00:04 ip-172-30-5-251 compiler-explorer:      at emitNone (events.js:111:20)
Nov 12 15:00:04 ip-172-30-5-251 compiler-explorer:      at IncomingMessage.emit (events.js:208:7)
Nov 12 15:00:04 ip-172-30-5-251 compiler-explorer:      at endReadableNT (_stream_readable.js:1055:12)
Nov 12 15:00:04 ip-172-30-5-251 compiler-explorer:      at _combinedTickCallback (internal/process/next_tick.js:138:11)
Nov 12 15:00:04 ip-172-30-5-251 compiler-explorer:      at process._tickDomainCallback (internal/process/next_tick.js:218:9)
```

also:

```
ov 12 15:00:04 ip-172-30-5-251 compiler-explorer:  #033[32minfo#033[39m: Fetching compilers from remote source https://www.godbolt.ms:443
Nov 12 15:00:04 ip-172-30-5-251 compiler-explorer:  #033[33mwarn#033[39m: Failed www.godbolt.ms:443 : timeout, retrying
```
