### ISSUE TITLE
When beta restarts we see a spam of restartings

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1224]
Whenever we do a beta restart we get a bunch of restarts: (seemingly not when we restart prod, thankfully). All ends up ok, but this is mysterious

```
16 events matched your node.js exit search in the past minute.
Dec 13 08:36:13 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:13 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:13 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:13 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:13 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:13 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:13 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:13 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:13 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:14 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:14 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:14 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:14 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:14 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:14 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
Dec 13 08:36:14 ip-172-30-0-227 unified-beta: Program node app.js --env amazon --port 10240 --static out/dist --archivedVersions /opt/compiler-explorer-archive --env beta --ensureNoIdClash exited with code 1
```

**Comment by partouf** [comment]
ahh that could be it, yes

**Comment by mattgodbolt** [comment]
Looks like the current working directory is gone (?). Maybe something funky with the new(er) way we update things. Doesn't affect master it seems.

**Comment by mattgodbolt** [comment]
With the current beta on `--debug` we got a clue!!

```

Mar 21 06:44:57 ip-172-30-0-111 unified-beta:  Starting child process with 'node app.js --env amazon --port 10240 --static out/dist --env beta --debug --ensureNoIdClash'
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:  module.js:540
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:      throw err;
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:      ^
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:  Error: Cannot find module 'nopt'
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:      at Function.Module._resolveFilename (module.js:538:15)
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:      at Function.Module._load (module.js:468:25)
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:      at Module.require (module.js:587:17)
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:      at require (internal/module.js:11:18)
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:      at Object.<anonymous> (/compiler-explorer/app.js:29:14)
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:      at Module._compile (module.js:643:30)
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:      at Object.Module._extensions..js (module.js:654:10)
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:      at Module.load (module.js:556:32)
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:      at tryModuleLoad (module.js:499:12)
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:      at Function.Module._load (module.js:491:3)
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:  Thu Mar 21 2019 11:44:57 GMT+0000 (UTC)
Mar 21 06:44:57 ip-172-30-0-111 unified-beta:  Thu Mar 21 2019 11:44:57 GMT+0000 (UTC)
```

**Comment by mattgodbolt** [comment]
So again points to somehow the way beta updates means it doesn't stop running before the cwd/`node_modules` are torn down and rebuilt? No idea :)

**Comment by partouf** [comment]
Doesn't make any sense. The docker instance only gets launched until all the new files are in place.

**Comment by partouf** [comment]
As discussed in slack, it seems that 'service compiler-explorer stop' did not stop the unified-beta container, so it might have been that some files may have been locked/busy/old and caused issues launching a new beta docker container.

Have tested a change it and watched the journalctl logging confirm it stopped with the change and restarted beta with the change. https://github.com/mattgodbolt/compiler-explorer-image/commit/3d3af6ae775a617c4c249341a5ba716c002664be

We'll have to wait and see if this *really* fixes it...

**Comment by RabsRincon** [comment]
We have not seen this sice. Great job @partouf :)
