### ISSUE TITLE
VC parser error: Cannot read property 'splice' of null

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1337]
```
Apr 03 02:39:19 ip-172-30-1-176 unified:  error: Error during compilation TypeError: Cannot read property 'splice' of null
Apr 03 02:39:19 ip-172-30-1-176 unified:      at checkUsedDatadefLabels (/compiler-explorer/lib/asm-parser-vc.js:149:20)
Apr 03 02:39:19 ip-172-30-1-176 unified:      at asmLines.forEach.line (/compiler-explorer/lib/asm-parser-vc.js:266:13)
Apr 03 02:39:19 ip-172-30-1-176 unified:      at Array.forEach (<anonymous>)
Apr 03 02:39:19 ip-172-30-1-176 unified:      at AsmParser.processAsm (/compiler-explorer/lib/asm-parser-vc.js:176:18)
Apr 03 02:39:19 ip-172-30-1-176 unified:      at AsmParser.process (/compiler-explorer/lib/asm-parser.js:465:21)
Apr 03 02:39:19 ip-172-30-1-176 unified:      at WineVcCompiler.processAsm (/compiler-explorer/lib/base-compiler.js:612:25)
Apr 03 02:39:19 ip-172-30-1-176 unified:      at compileToAsmPromise.then.then.then.then.result (/compiler-explorer/lib/base-compiler.js:572:51)
Apr 03 02:39:19 ip-172-30-1-176 unified:  info: 198.72.210.0 "POST /api/compiler/cl_new_arm64/compile" 200
Apr 03 02:39:19 ip-172-30-1-176 unified:      at <anonymous>
```

**Comment by mattgodbolt** [comment]
Still happening a fair bit.
