### ISSUE TITLE
TypeError: Unable to get property '$order' of undefined or null reference

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1367]
https://sentry.io/organizations/compiler-explorer/issues/1010579692/?referrer=github_plugin

```
TypeError: Unable to get property '$order' of undefined or null reference
  at Array.prototype.sort (/dist/bundle.a733fa9cbc7e1e361a7e.js)
  at Anonymous function (./static/panes/compiler.js:1651:1)
  at this (./static/panes/compiler.js:1645:1)
  at subs (./static/panes/compiler.js:1626:1)
  at this (./static/hub.js:221:1)
...
(29 additional frame(s) were not displayed)
```

**Comment by RabsRincon** [comment]
Probably has to do with selectize.js by the looks of the mentioned $order key

**Comment by mattgodbolt** [comment]
Yeah it's odd it's started happening. I moved from yarn back to npm and I bet a ton of package versions changed...

**Comment by mattgodbolt** [comment]
Sentry issue: [COMPILER-EXPLORER-4HH](https://sentry.io/organizations/compiler-explorer/issues/1010583379/?referrer=github_plugin)

**Comment by mattgodbolt** [comment]
```selectize.js:1597 Uncaught TypeError: Cannot read property '$order' of undefined
    at selectize.js:1597
    at Array.sort (<anonymous>)
    at v.refreshOptions (selectize.js:1595)```

repro'd locally when switching languages (from C++ to Ada in my case)
