### ISSUE TITLE
TypeError: w.optgroups[e] is undefined

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1368]
https://sentry.io/organizations/compiler-explorer/issues/1010582849/?referrer=github_plugin

```
TypeError: w.optgroups[e] is undefined
  at sourceFunc (./static/panes/compiler.js:1651:1)
  at this (./static/panes/compiler.js:1650:1)
  at subs (./static/panes/compiler.js:1633:1)
  at this (./static/hub.js:221:1)
  at this (./static/panes/editor.js:780:1)
...
(28 additional frame(s) were not displayed)
```

**Comment by mattgodbolt** [comment]
Hopefully fixed by the fix for #1367
