### ISSUE TITLE
Site outage: Nodes being killed by ELB health check

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1393]
We're seeing nodes being killed by the ELB health check. Had the "spot-beta" get taken down twice in the last 4 hours. Both times ELB health check failed. Output in the logs:

```
May 24 09:23:37 ip-172-30-1-164 amazon:  info: 128.187.116.0 "POST /api/compiler/g91/compile" 200 
May 24 09:23:37 ip-172-30-1-164 amazon:  warn: Skipping temporary file clean up as compiler environment is busy 
May 24 09:23:38 ip-172-30-1-164 amazon:  info: 2001:44b8:312e:fe00:3d27:0:0:0 "POST /api/compiler/clang800/compile" 200 
May 24 09:23:38 ip-172-30-1-164 amazon:  info: 140.78.145.0 "POST /api/compiler/ppc64leclang/compile" 200 
May 24 09:23:40 ip-172-30-1-164 amazon:  info: 50.249.101.0 "POST /api/compiler/g91/compile" 200 
May 24 09:23:40 ip-172-30-1-164 amazon:  info: 83.142.187.0 "POST /api/compiler/g82/compile" 200 
May 24 09:23:40 ip-172-30-1-164 amazon:  info: 128.187.116.0 "POST /api/compiler/g91/compile" 200 
May 24 09:25:28 ip-172-30-1-164 systemd-logind:  Power key pressed.
May 24 09:25:28 ip-172-30-1-164 systemd-logind:  Powering Off...
May 24 09:25:28 ip-172-30-1-164 systemd-logind:  System is powering down.
May 24 09:25:28 ip-172-30-1-164 systemd:  Stopped Unattended Upgrades Shutdown.
May 24 09:25:28 ip-172-30-1-164 systemd:  Stopped target Host and Network Name Lookups.
May 24 09:25:28 ip-172-30-1-164 systemd:  Unmounting RPC Pipe File System...
May 24 09:25:28 ip-172-30-1-164 systemd:  Closed Load/Save RF Kill Switch Status /dev/rfkill Watch.
May 24 09:25:28 ip-172-30-1-164 systemd:  Stopping Availability of block devices...
May 24 09:25:28 ip-172-30-1-164 systemd:  Stopped target Cloud-init target.
```

and

```
May 24 06:29:55 ip-172-30-0-191 amazon:  info: 213.254.205.0 "POST /api/popularArguments/vcpp_v19_20_x64" 200 
May 24 06:29:55 ip-172-30-0-191 amazon:  info: 213.254.205.0 "POST /api/compiler/clang800/compile" 200 
May 24 06:29:55 ip-172-30-0-191 amazon:  info: 213.254.205.0 "POST /api/compiler/vcpp_v19_20_x64/compile" 200 
May 24 06:29:55 ip-172-30-0-191 amazon:  info: 213.254.205.0 "POST /api/compiler/g91/compile" 200 
May 24 06:29:55 ip-172-30-0-191 amazon:  info: 185.220.101.0 "POST /api/compiler/clang800/compile" 200 
May 24 06:29:55 ip-172-30-0-191 amazon:  info: 213.254.205.0 "POST /api/popularArguments/vcpp_v19_20_x64" 200 
May 24 06:29:56 ip-172-30-0-191 amazon:  info: 66.70.178.0 "POST /api/compiler/cl_new_64/compile" 200 
May 24 06:32:37 ip-172-30-0-191 systemd-logind:  Power key pressed.
May 24 06:32:37 ip-172-30-0-191 systemd-logind:  Powering Off...
May 24 06:32:38 ip-172-30-0-191 systemd-logind:  System is powering down.
May 24 06:32:38 ip-172-30-0-191 systemd:  Stopped target Cloud-init target.
May 24 06:32:40 ip-172-30-0-191 amazon:  warn: Timeout for /usr/local/bin/firejail --quiet,--deterministic-exit-code,--terminate-orphans,--profile=etc/firejail/execute.profile,--private=/tmp/compiler-explorer-compiler119424-1246-1rf4crh.tkgv,--private-cwd,/opt/compiler-explorer/gcc-9.1.0/bin/g++,-g,-o,./output.s,-masm=intel,-S,-fdiagnostics-color=always,-O3,-std=c++17,./example.cpp after 20000ms 
May 24 06:32:40 ip-172-30-0-191 amazon:  warn: Timeout for /usr/local/bin/firejail --quiet,--deterministic-exit-code,--terminate-orphans,--profile=etc/firejail/execute.profile,--private=/tmp/compiler-explorer-compiler119424-1246-xeyhku.7svjd,--private-cwd,/opt/compiler-explorer/clang-8.0.0/bin/clang++,-g,-o,./output.s,-mllvm,--x86-asm-syntax=intel,-S,--gcc-toolchain=/opt/compiler-explorer/gcc-8.3.0,-fcolor-diagnostics,-fno-crash-diagnostics,-isystem/opt/compiler-explorer/libs/fmt/trunk/include,./example.cpp after 20000ms 
May 24 06:32:40 ip-172-30-0-191 amazon:  warn: Timeout for /usr/local/bin/firejail --quiet,--deterministic-exit-code,--terminate-orphans,--profile=etc/firejail/execute.profile,--private=/tmp/compiler-explorer-compiler119424-1246-14uhn5k.mgg9,--private-cwd,/opt/compiler-explorer/gcc-9.1.0/bin/g++,-g,-o,./output.s,-masm=intel,-S,-fdiagnostics-color=always,-O2,-std=c++11,./example.cpp after 20000ms 
May 24 06:32:40 ip-172-30-0-191 amazon:  warn: Timeout for /usr/local/bin/firejail --quiet,--deterministic-exit-code,--terminate-orphans,--profile=etc/firejail/execute.profile,--private=/tmp/compiler-explorer-compiler119424-1246-jsdq4e.mbtsl,--private-cwd,/opt/compiler-explorer/clang-8.0.0/bin/clang++,-g,-o,./output.s,-mllvm,--x86-asm-syntax=intel,-S,--gcc-toolchain=/opt/compiler-explorer/gcc-8.3.0,-fcolor-diagnostics,-fno-crash-diagnostics,-O3,-std=c++14,-stdlib=libc++,./example.cpp after 20000ms 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 87.241.189.0 "POST /api/popularArguments/g91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 185.42.125.0 "POST /api/popularArguments/clang800" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 192.198.151.0 "POST /api/popularArguments/g91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 213.254.205.0 "POST /api/popularArguments/clang800" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 213.254.205.0 "POST /api/popularArguments/g91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 2a02:aa13:6203:5e00:6839:0:0:0 "POST /api/popularArguments/clang_trunk" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 128.214.138.0 "POST /api/popularArguments/g91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 213.254.205.0 "POST /api/popularArguments/vcpp_v19_20_x64" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 185.220.101.0 "POST /api/popularArguments/g91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 185.220.101.0 "POST /api/popularArguments/clang800" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 145.101.165.0 "POST /api/popularArguments/vcpp_v19_20_x64" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 145.101.165.0 "POST /api/popularArguments/g91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 192.198.151.0 "POST /api/popularArguments/g82" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 89.87.166.0 "POST /api/popularArguments/g91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 213.206.248.0 "POST /api/popularArguments/g82" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 89.250.166.0 "POST /api/popularArguments/g91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 87.241.189.0 "POST /api/popularArguments/g91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 128.130.251.0 "POST /api/popularArguments/cg91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 128.130.251.0 "POST /api/popularArguments/cg91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 185.42.125.0 "POST /api/popularArguments/clang800" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 192.198.151.0 "POST /api/popularArguments/g91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 213.254.205.0 "POST /api/popularArguments/vcpp_v19_20_x64" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 185.220.101.0 "POST /api/popularArguments/g91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 89.250.166.0 "POST /api/popularArguments/g91" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: 149.201.117.0 "POST /api/popularArguments/clang_trunk" 200 
May 24 06:32:40 ip-172-30-0-191 amazon:  info: Shutting down WINE server complex 
```

**Comment by mattgodbolt** [comment]
Seems it's multiple firejails timing out, if the latter shutdown case is to be believed

**Comment by mattgodbolt** [comment]
Another site failure:

```
May 24 06:28:05 ip-172-30-0-16 amazon:  info: 213.254.205.0 "POST /api/compiler/clang800/compile" 200 
May 24 06:28:05 ip-172-30-0-16 amazon:  info: 213.254.205.0 "POST /api/popularArguments/vcpp_v19_20_x64" 200 
May 24 06:28:07 ip-172-30-0-16 amazon:  info: 193.173.39.0 "POST /api/popularArguments/vcpp_v19_16_x86" 200 
May 24 06:29:44 ip-172-30-0-16 systemd-logind:  Power key pressed.
May 24 06:29:45 ip-172-30-0-16 systemd-logind:  Powering Off...
May 24 06:29:48 ip-172-30-0-16 systemd-logind:  System is powering down.
May 24 06:29:49 ip-172-30-0-16 amazon:  error: Error during compilation: spawn ENOMEM {"errno":"ENOMEM","code":"ENOMEM","syscall":"spawn","stack":"Error: spawn ENOMEM\n    at ChildProcess.spawn (internal/child_process.js:366:11)\n    at Object.spawn (child_process.js:538:9)\n    at executeDirect (/compiler-explorer-image/.deploy/lib/exec.js:64:33)\n    at executeFirejail (/compiler-explorer-image/.deploy/lib/exec.js:338:12)\n    at Object.execute (/compiler-explorer-image/.deploy/lib/exec.js:358:12)\n    at DefaultCompiler.exec (/compiler-explorer-image/.deploy/lib/base-compiler.js:103:21)\n    at DefaultCompiler.runCompiler (/compiler-explorer-image/.deploy/lib/base-compiler.js:124:21)\n    at tempFileAndDirPromise.then.info (/compiler-explorer-image/.deploy/lib/base-compiler.js:461:49)"} 
May 24 06:29:49 ip-172-30-0-16 amazon:  info: 145.101.165.0 "POST /api/compiler/g91/compile" 200 
May 24 06:29:49 ip-172-30-0-16 amazon:  warn: Timeout for /usr/local/bin/firejail --quiet,--deterministic-exit-code,--terminate-orphans,--profile=etc/firejail/execute.profile,--private=/tmp/compiler-explorer-compiler119424-1353-1r1te58.7npk,--private-cwd,/opt/compiler-explorer/gcc-9.1.0/bin/g++,-g,-o,./output.s,-masm=intel,-S,-fdiagnostics-color=always,-O3,-std=c++17,./example.cpp after 20000ms 
May 24 06:29:49 ip-172-30-0-16 amazon:  warn: Timeout for /usr/local/bin/firejail --quiet,--deterministic-exit-code,--terminate-orphans,--profile=etc/firejail/execute.profile,--private=/tmp/compiler-explorer-compiler119424-1353-5njw9g.5r3p5,--private-cwd,/opt/compiler-explorer/gcc-snapshot/bin/g++,-g,-o,./output.s,-masm=intel,-S,-fdiagnostics-color=always,-O3,-std=c++14,-Wall,-Wextra,-pedantic,-Wunreachable-code,-Wdeprecated,./example.cpp after 20000ms 
May 24 06:29:49 ip-172-30-0-16 amazon:  info: Shutting down WINE server complex 
May 24 06:29:49 ip-172-30-0-16 amazon:  info: 145.101.165.0 "POST /api/popularArguments/vcpp_v19_20_x64" 200 
May 24 06:29:49 ip-172-30-0-16 amazon:  info: 87.241.189.0 "POST /api/popularArguments/g91" 200 
```

**Comment by mattgodbolt** [comment]
We've lost the memory usage limiting! Of course :)

**Comment by mattgodbolt** [comment]
Deploying to prod now
