### ISSUE TITLE
short links broken on secondary site

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#1432]
https://compiler-explorer.com/ short links are broken. browser:

```
Uncaught DOMException: Failed to execute 'pushState' on 'History': A history state object with URL 'http://compiler-explorer.com/z/vanRkM' cannot be created in a document with origin 'https://compiler-explorer.com' and URL 'https://compiler-explorer.com/'.
    at History.pushState (https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:96:70536)
    at https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:88:110570
    at t (https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:96:75392)
    at https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:96:76726
    at https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:96:76141
    at N (https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:37:82129)
    at Object.<anonymous> (https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:37:82331)
    at Object.success (https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:37:75483)
    at h (https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:37:23403)
    at Object.fireWith [as resolveWith] (https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:37:24152)
    at n (https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:37:62248)
    at XMLHttpRequest.<anonymous> (https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:37:67251)
    at XMLHttpRequest.o (https://compiler-explorer.com/dist/bundle.5adbe814861037431ec6.js:64:13622)
sentry.io/api/102028/store/?sentry_key=8e4614f649ad4e3faf3e7e8827b935f9&sentry_version=7:1 Failed to load resource: the server responded with a status of 403 (FORBIDDEN)
```

Additionally, sentry blocked it

**Comment by partouf** [comment]
CSP change #1431 did fix loading shortlinks from compiler-explorer.com, but did not fix creating the link

**Comment by partouf** [comment]
Just noticed it's trying to go to an http shortlink url instead of https

**Comment by partouf** [comment]
The /shortener call returns a link to http://compiler-explorer.com/z/id and the way that gets composed is by using request.protocol + ://
So this shouldn't be really any different from godbolt.org, but apparently, it is. Will have something to do with the frontend at either amazon or the nginx?

**Comment by apmorton** [comment]
[godbolt.org](https://github.com/mattgodbolt/compiler-explorer-image/blob/master/terraform/cloudfront.tf#L12) vs [compiler-explorer.com](https://github.com/mattgodbolt/compiler-explorer-image/blob/master/terraform/cloudfront.tf#L146)

**Comment by partouf** [comment]
ahh figured as much, the load balancer also only has the godbolt certificate. Not sure it's possible to actually fix this?

**Comment by partouf** [comment]
Fixed by adding cert to loadbalancer and setting up the cloudfront forwarding to do https instead of http

**Comment by apmorton** [comment]
maybe reopen this (or a new issue) to track the sentry bit? presumably sentry just needs to be told to allow requests from `compiler-explorer.com`

**Comment by mattgodbolt** [comment]
I filed a separate bug; thanks for reminding me @apmorton
