### ISSUE TITLE
How to add a C compiler to Linux CE instance using wine?

### ISSUE THREAD

**Issue by paulsapps** [mattgodbolt/compiler-explorer#1447]
I've attempted to add a compiler and at this point its driving me nuts..

In my `/etc/config.cdefaults.properties` I have:

```
ompilers=PSYQ
defaultCompiler=PSYQ
compiler.PSYQ.exe=/psyq/bin/CCPSX.EXE
compiler.PSYQ.name=PSX CC
compiler.PSYQ.type=wine-vc
postProcess=
demangler=c++filt
objdumper=objdump
supportsBinary=true
binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|\.plt.*)$
stubRe=\bmain\b
stubText=int main(void){return 0;/*stub provided by Compiler Explorer*/}
```

When I attempt to start the instance it results in this:

```
nfo: Gathering PSYQ version information on /psyq/bin/CCPSX.EXE
error: Unable to get version for compiler '/psyq/bin/CCPSX.EXE' - TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
```

To get past this I can prefix `compiler.PSYQ.exe=/psyq/bin/CCPSX.EXE` with `wine` but this seems wrong and then just leads it onto fail when it a compile request is submitted.

As far as I can tell it should be running under wine anyway because of

```
function needsWine(command) {
    return command.match(/\.exe$/i) && process.platform === 'linux';
}
```

In `/lib/exec.js` ?

How can I debug this to get it working? I'm really not sure what to try next.

**Comment by partouf** [comment]
It looks that we forgot to define the wine executable outside of the Amazon environment.

If you add this line and alter the path so that it points to your wine64 executable, I'm guessing it should be fixed:
wine=/opt/wine-stable/bin/wine64

**Comment by paulsapps** [comment]
So the only stuff in etc/config I have is:

c.local.properties

```
compilers=PSYQ
defaultCompiler=PSYQ
compiler.PSYQ.exe=/psyq/bin/CCPSX.EXE
compiler.PSYQ.name=PSX CC
compiler.PSYQ.type=wine-vc
postProcess=
demangler=c++filt
objdumper=objdump
supportsBinary=true
binaryHideFuncRe=^(__.*|_(init|start|fini)|(de)?register_tm_clones|call_gmon_start|frame_dummy|\.plt.*)$
stubRe=\bmain\b
stubText=int main(void){return 0;/*stub provided by Compiler Explorer*/}
```

execution.local.properties

```
sandboxType=none
executionType=none

wine=/usr/bin/wine
wineserver=/usr/bin/wineserver
wineprefix=/root/.wine/
```

And when I try to start CE I get this:

```
Starting child process with '/usr/bin/node ./app.js'
Watching directory '/psyq/ce/app.js' for changes.
Press rs for restarting the process.
Watching directory '/psyq/ce/lib' for changes.
Press rs for restarting the process.
Watching directory '/psyq/ce/etc/config' for changes.
Press rs for restarting the process.
info: properties hierarchy: defaults, dev, dev.linux, linux, 2cc5d896ab0a, local
info: Reading properties from ./etc/config with hierarchy defaults,dev,dev.linux,linux,2cc5d896ab0a,local
info: Initialising WINE in undefined
info: Creating directory undefined
error: AWS Init Promise error (shutting down)The "path" argument must be one of type string, Buffer, or URL. Received type undefined {"stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"path\" argument must be one of type string, Buffer, or URL. Received type undefined\n    at Object.mkdirSync (fs.js:749:3)\n    at initialiseWine (/psyq/ce/lib/exec.js:218:12)\n    at process._tickCallback (internal/process/next_tick.js:68:7)\n    at Function.Module.runMain (internal/modules/cjs/loader.js:832:11)\n    at startup (internal/bootstrap/node.js:283:19)\n    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)"}
Program /usr/bin/node ./app.js exited with code 1
```

Any idea what I've screwed up now?

**Comment by mattgodbolt** [comment]
For those following along, we spotted (in slack) that the `wineprefix` needs to be `winePrefix`

**Comment by paulsapps** [comment]
So the issues where wineprefix  -> winePrefix, wineserver -> wineServer. And in lib/exec.js some hacks had to be done to prevent it filtering out system level env vars which the compiler I was adding required to function correctly.

Thanks for the help :).
