### ISSUE TITLE
[BUG] Compiler crash when emitting llvm-ir

### ISSUE THREAD

**Issue by Azoy** [mattgodbolt/compiler-explorer#1741]
When trying to emit the output llvm-ir for languages like Swift and Rust, the compiler-explorer compiler crashes with: 
```
Internal Compiler Explorer error: TypeError: Cannot read property 'length' of undefined
    at Demangler.collectLabels (/compiler-explorer-image/.deploy/lib/demangler.js:103:45)
    at Demangler.process (/compiler-explorer-image/.deploy/lib/demangler.js:215:18)
    at SwiftCompiler.postProcessAsm (/compiler-explorer-image/.deploy/lib/base-compiler.js:851:26)
    at /compiler-explorer-image/.deploy/lib/base-compiler.js:808:69
Compiler returned: -1
```

You can see it here: https://swift.godbolt.org/z/4PFw79

**Comment by RabsRincon** [comment]
Hi! Thanks for the report. I've pushed some changes that should hopefully fix this. It should hit the live site this week :)
