### ISSUE TITLE
Make more windows-friendly

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#304]
Maybe moving to a `grunt`-based setup would help move some of the unixy things the `Makefile` does into stuff that will "just work" on windows.

**Comment by ubsan** [comment]
This could also be fixed by adding `npx` to the `package.json`, and then using

```
npm install
npm start
```

instead of make; if Linux folx still wanted a single command, we could rewrite the makefile to look something like

```
all: install
        npm start

install:
        npm install
```

although with the "find where npm is installed" code; that code is usually unnecessary on personal installations.

**Comment by jaredwy** [comment]
@ubsan
this already happens for windows.

https://github.com/mattgodbolt/compiler-explorer/blob/master/package.json#L89

**Comment by ubsan** [comment]
I'd also be interested in anyone who has an ubuntu machine trying it out; my point in all of this is that this should basically be a closed issue, since npm Just Works (tm).

**Comment by wimo7083** [comment]
I'd like to continue to work on this. I think there's a problem with a recently pinned dependency. 

`npm install npx --save-dev`
```powershell
PS C:\Users\William.Montgomery\Desktop\compiler-explorer> npm install npx --save-dev
npm notice created a lockfile as package-lock.json. You should commit this file.
+ npx@10.2.0
added 484 packages in 73.179s
```

`npm install`

```powershell
λ npm install
npm ERR! code 1
npm ERR! Command failed: C:\Program Files\Git\cmd\git.EXE checkout ^3.1.2
npm ERR! error: pathspec '^3.1.2' did not match any file(s) known to git
npm ERR!

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\William.Montgomery\AppData\Roaming\npm-cache\_logs\2018-11-01T18_34_54_414Z-debug.log
```

logs
```powershell
λ tail -n 20 C:\Users\William.Montgomery\AppData\Roaming\npm-cache\_logs\2018-11-01T18_19_53_680Z-debug.log
2238 silly saveTree +-- winston@2.4.4
2238 silly saveTree +-- wolfy87-eventemitter@5.2.5
2238 silly saveTree `-- yarn@1.12.1
2239 verbose stack Error: Command failed: C:\Program Files\Git\cmd\git.EXE checkout ^3.1.2
2239 verbose stack error: pathspec '^3.1.2' did not match any file(s) known to git
2239 verbose stack
2239 verbose stack     at ChildProcess.exithandler (child_process.js:275:12)
2239 verbose stack     at emitTwo (events.js:126:13)
2239 verbose stack     at ChildProcess.emit (events.js:214:7)
2239 verbose stack     at maybeClose (internal/child_process.js:925:16)
2239 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
2240 verbose cwd C:\Users\William.Montgomery\Desktop\compiler-explorer
2241 verbose Windows_NT 10.0.16299
2242 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
2243 verbose node v8.11.4
2244 verbose npm  v5.6.0
2245 error code 1
2246 error Command failed: C:\Program Files\Git\cmd\git.EXE checkout ^3.1.2
2246 error error: pathspec '^3.1.2' did not match any file(s) known to git
2247 verbose exit [ 1, true ]
```
The only package similar to this is this [fork](https://github.com/mattgodbolt/compiler-explorer/blob/968277d38ca9e1847579c30efe89640bdc4abff0/package.json#L28)

Which is owned by the [commiter ](https://github.com/mattgodbolt/compiler-explorer/commit/b89d10eb98a7aaadcb3f37ab8fafebfcafdd7001)of the change @RabsRincon 

When I install it directly:
```powershell
compiler-explorer   master ± 
λ npm install RabsRincon/cookieconsent#^3.1.2
+ cookieconsent@3.1.2
added 1 package in 96.897s
```

And then view how the package looks. 

```powershell
λ git diff package.json
warning: LF will be replaced by CRLF in package.json.
The file will have its original line endings in your working directory
diff --git a/package.json b/package.json
index c9a55374..f1e5dea8 100644
--- a/package.json
+++ b/package.json
@@ -25,7 +25,7 @@
     "clipboard": "^1.7.1",
     "compiler-opt-info": "0.0.4",
     "compression": "^1.7.1",
-    "cookieconsent": "RabsRincon/cookieconsent#^3.1.2",
+    "cookieconsent": "github:RabsRincon/cookieconsent#3.1.2",
     "cross-env": "^5.1.3",
     "denodeify": "^1.2.1",
     "es6-promise": "^4.1.1",
@@ -76,6 +76,7 @@
     "istanbul": "^0.4.5",
     "mocha": "^3.3.0",
     "nock": "^9.1.4",
+    "npx": "^10.2.0",
     "requirejs": "*",
     "style-loader": "^0.19.0",
     "supervisor": "*",
```

When I remove the `^` in front off the version I get the same error. 

<details>
<summary> npm start </summary>

```
λ npm start

> compiler-explorer@0.0.3 start C:\Users\William.Montgomery\Desktop\compiler-explorer
> npx webpack && cross-env NODE_ENV=LOCAL node app.js

Child
    Hash: e31860306c109defee31
    Version: webpack 3.12.0
    Time: 3174ms


/// loading of compilers

info: =======================================
info:   git release 968277d38ca9e1847579c30efe89640bdc4abff0
info:   serving static files from 'static'
info:   Listening on http://localhost:10240/
info: =======================================
info: ::1 "GET /" 200
info: ::1 "GET /source/builtin/list" 200

```

</details>

**Comment by wimo7083** [comment]
Since this issue was created the project switched to yarn. 
`yarn install` works perfectly fine
`npm install` does not.

**Comment by wimo7083** [comment]
After reading through the documentation more, there's a fairly easy [setup](https://github.com/mattgodbolt/compiler-explorer/blob/master/docs/WindowsNative.md) That has been updated pretty recently. 

Maybe this should be closed?
