### ISSUE TITLE
Unexpected render request

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#353]
From sentry:
https://sentry.io/matt-godbolt/compiler-explorer/issues/242983870/

```
Error: Unexpected render request

Error: Unexpected render request
    at t.render (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:62:3085)
    at e.shouldUpdateHTML (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:67:15089)
    at e._finishRendering (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:61:6529)
    at e._render (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:61:4311)
    at e.renderWithManyUpdates (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:61:2521)
    at t._renderLines (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:61:1891)
    at t._viewOverlaysRender (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:67:14334)
    at t._viewOverlaysRender (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:67:17424)
    at t.render (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:67:14185)
    at t._actualRender (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:76:18031)
    at http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:76:17218
    at B (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:75:29550)
    at t._renderNow (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:76:17196)
    at t._flushAccumulatedAndRenderNow (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:76:4226)
    at Object.visibleRangeForPosition2 (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:76:6808)
    at e.visibleRangeForPosition2 (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:60:3849)
    at Function.e.createMouseTargetFromHitTestPosition (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:60:10327)
    at Function.e._hitTestViewLines (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:60:8793)
    at Function.e._createMouseTarget (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:60:6349)
    at e.createMouseTarget (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:60:5761)
    at t._createMouseTarget (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:60:17148)
    at t._onMouseMove (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:60:17613)
    at t._destination (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:60:15029)
    at t._handle (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:60:14054)
    at i.handler (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:60:13826)
    at d (http://gcc.beta.godbolt.org/v/ba7c1e588bc42d8d1c7b2b91a89cd1c27c9996ec/ext/monaco-editor/min/vs/editor/editor.main.js:36:3201)
    at http://gcc.beta.godbolt.org/v/ba7...
  at t.render (vs/editor/file:/C:/Alex/src/vscode/src/vs/editor/browser/viewParts/glyphMargin/glyphMargin.ts:209:9)
  at render (vs/editor/file:/C:/Alex/src/vscode/src/vs/editor/browser/view/viewOverlays.ts:149:31)
  at shouldUpdateHTML (vs/editor/file:/C:/Alex/src/vscode/src/vs/editor/browser/view/viewLayer.ts:636:12)
  at _finishRendering (vs/editor/file:/C:/Alex/src/vscode/src/vs/editor/browser/view/viewLayer.ts:489:7)
  at _render (vs/editor/file:/C:/Alex/src/vscode/src/vs/editor/browser/view/viewLayer.ts:385:14)
...
(25 additional frame(s) were not displayed)
```

Getting a bunch of these on the beta site. Unclear what's going on.

**Comment by RabsRincon** [comment]
`at t.render (vs/editor/file:/C:/Alex/src/vscode/src/vs/editor/browser/viewParts/glyphMargin/glyphMargin.ts:209:9)` makes me think it's releated to the `onMouseMove` of the compiler, but it's just a wild guess

**Comment by mattgodbolt** [comment]
Looks like it's fixed: hasn't been seen today!

**Comment by mattgodbolt** [comment]
Still happens...but I suspect I know why now...

**Comment by foxable** [comment]
I observed the same exception in one of my projects using monaco-editor, but could not reproduce it in isolation just yet. This issue was the only one I could find referring to this specific exception. I would be glad if you could share any insights that you gained on the cause of the exception.
