### ISSUE TITLE
node js crash out with url parsing

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#465]
```
Jun 14 11:09:15 a769407e1636 gcc:  info: 109.100.187.71 - - [14/Jun/2017:16:09:15 +0000] "POST /api/compiler/g71/compile HTTP/1.0" 200 - "-" "Amazon CloudFront" 
Jun 14 11:09:17 a769407e1636 gcc:  url.js:88 
Jun 14 11:09:17 a769407e1636 gcc:      throw new TypeError('Parameter "url" must be a string, not ' + typeof url); 
Jun 14 11:09:17 a769407e1636 gcc:      ^ 
Jun 14 11:09:17 a769407e1636 gcc:  TypeError: Parameter "url" must be a string, not undefined 
Jun 14 11:09:17 a769407e1636 gcc:      at Url.parse (url.js:88:11) 
Jun 14 11:09:17 a769407e1636 gcc:      at Object.urlParse [as parse] (url.js:82:5) 
Jun 14 11:09:17 a769407e1636 gcc:      at IncomingMessage.<anonymous> (/compiler-explorer/app.js:464:30) 
Jun 14 11:09:17 a769407e1636 gcc:      at emitNone (events.js:91:20) 
Jun 14 11:09:17 a769407e1636 gcc:      at IncomingMessage.emit (events.js:185:7) 
Jun 14 11:09:17 a769407e1636 gcc:      at endReadableNT (_stream_readable.js:974:12) 
Jun 14 11:09:17 a769407e1636 gcc:      at _combinedTickCallback (internal/process/next_tick.js:74:11) 
Jun 14 11:09:17 a769407e1636 gcc:      at process._tickCallback (internal/process/next_tick.js:98:9) 
Jun 14 11:09:17 a769407e1636 gcc:  Wed Jun 14 2017 16:09:17 GMT+0000 (UTC) 
Jun 14 11:09:17 a769407e1636 gcc:  Program node app.js --env amazon --port 10240 --lang C++ --static out/dist --archivedVersions /opt/compiler-explorer-archive exited with code 1 
```

**Comment by mattgodbolt** [comment]
Presumably a malformed request. Surprised that it caused node.js to exit

**Comment by mattgodbolt** [comment]
Happened again:

```
Aug 17 03:12:46 9427ee778ff7 gcc:  url.js:81 
Aug 17 03:12:46 9427ee778ff7 gcc:      throw new TypeError('Parameter "url" must be a string, not ' + typeof url); 
Aug 17 03:12:46 9427ee778ff7 gcc:      ^ 
Aug 17 03:12:46 9427ee778ff7 gcc:  TypeError: Parameter "url" must be a string, not undefined 
Aug 17 03:12:46 9427ee778ff7 gcc:      at Url.parse (url.js:81:11) 
Aug 17 03:12:46 9427ee778ff7 gcc:      at Object.urlParse [as parse] (url.js:75:5) 
Aug 17 03:12:46 9427ee778ff7 gcc:      at IncomingMessage.<anonymous> (/compiler-explorer/app.js:471:30) 
Aug 17 03:12:46 9427ee778ff7 gcc:      at emitNone (events.js:91:20) 
Aug 17 03:12:46 9427ee778ff7 gcc:      at IncomingMessage.emit (events.js:185:7) 
Aug 17 03:12:46 9427ee778ff7 gcc:      at endReadableNT (_stream_readable.js:974:12) 
Aug 17 03:12:46 9427ee778ff7 gcc:      at _combinedTickCallback (internal/process/next_tick.js:80:11) 
Aug 17 03:12:46 9427ee778ff7 gcc:      at process._tickCallback (internal/process/next_tick.js:104:9) 
Aug 17 03:12:46 9427ee778ff7 gcc:  Thu Aug 17 2017 08:12:46 GMT+0000 (UTC) 
Aug 17 03:12:46 9427ee778ff7 gcc:  Program node app.js --env amazon --port 10240 --lang C++ --static out/dist --archivedVersions /opt/compiler-explorer-archive exited with code 1 
```

**Comment by mattgodbolt** [comment]
It's in the `shortUrlHandler`. Can't believe I didn't look at the stack...it's pretty obvious.
