### ISSUE TITLE
TypeError: Cannot read property 'conf' of undefined

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#511]
https://sentry.io/compiler-explorer/compiler-explorer/issues/397622639/

```
TypeError: Cannot read property 'conf' of undefined
  at apply (cppp-mode.js:27)
  at execCb (//v/26635231301bb99e89820eaa68c62a28988673ab/ext/requirejs/require.js:1696:32)
  at check (//v/26635231301bb99e89820eaa68c62a28988673ab/ext/requirejs/require.js:883:50)
  at apply (//v/26635231301bb99e89820eaa68c62a28988673ab/ext/requirejs/require.js:1139:33)
  at cb (//v/26635231301bb99e89820eaa68c62a28988673ab/ext/requirejs/require.js:134:22)
...
(10 additional frame(s) were not displayed)
```

**Comment by mattgodbolt** [comment]
Seems like a one-off...will monitor but probably a load issue.

**Comment by mattgodbolt** [comment]
Happened three times ever. Marking as fixed.
