### ISSUE TITLE
SyntaxError: Unexpected token var

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#534]
https://sentry.io/matt-godbolt/compiler-explorer/issues/328275102/

```
SyntaxError: Unexpected token var
  at None (/)
```

Not quite sure what's causing this, but clicking the link in the sentry issue seems to reproduce _something_ like the bug.

**Comment by mattgodbolt** [comment]
Actually, scratch that. seems the links in sentry are truncated. This comes up a lot though ... I wonder what it is

**Comment by mattgodbolt** [comment]
One referer was:
https://www.reddit.com/r/cpp/comments/71kx4m/is_this_language_defect_limitation_or_feature/

which leads to https://godbolt.org/g/U3tBPJ which loads just fine...I wonder what on earth this is...

**Comment by mattgodbolt** [comment]
This is the number one issue on Sentry at the moment. I'm perplexed!

**Comment by mattgodbolt** [comment]
I wonder if the truncation is actually being done somewhere. e.g. https://gcc.godbolt.org/#%7B%22version%22%3A3%2C%22filterAsm%22%3A%7B%22labels%22%3Atrue%2C%22directives%22%3Atrue%2C%22commentOnly%22%3Atrue%2C%22colouriseAsm%22%3Atrue%7D%2C%22compilers%22%3A%5B%7B%22sourcez%22%3A%22MQSwdgxgNgrgJgUwAQB4IGcAucQHsB8A… (including the ellipsis) leads to 

rison parser error:  missing ','
/v/06731e49e40ec2ded4d662d889bf8ee76b99e849/main.js:6 rison parser error:  missing ':'
/v/06731e49e40ec2ded4d662d889bf8ee76b99e849/main.js:6 Uncaught Error: rison decoder error: missing ':'
    at e.parser.i [as errorHandler] (/v/06731e49e40ec2ded4d662d889bf8ee76b99e849/main.js:9)
    at e.parser.parse (/v/06731e49e40ec2ded4d662d889bf8ee76b99e849/main.js:9)
    at Object.e.decode (/v/06731e49e40ec2ded4d662d889bf8ee76b99e849/main.js:9)
    at Object.e.decode_object (/v/06731e49e40ec2ded4d662d889bf8ee76b99e849/main.js:9)
    at o (/v/06731e49e40ec2ded4d662d889bf8ee76b99e849/main.js:10)
    at Object.s [as deserialiseState] (/v/06731e49e40ec2ded4d662d889bf8ee76b99e849/main.js:10)
    at HTMLDocument.i (/v/06731e49e40ec2ded4d662d889bf8ee76b99e849/main.js:36)
    at u (/v/06731e49e40ec2ded4d662d889bf8ee76b99e849/main.js:2)
    at c (/v/06731e49e40ec2ded4d662d889bf8ee76b99e849/main.js:2)
    at n (/v/06731e49e40ec2ded4d662d889bf8ee76b99e849/main.js:6)

**Comment by mattgodbolt** [comment]
```
stack
:
"Error: rison decoder error: missing ':'↵    at e.parser.i [as errorHandler] (http://localhost:10240/v/9ac1116a7f4e1044ca0ce648daa9db0667794ec1/main.js:9:24567)↵    at e.parser.parse (http://localhost:10240/v/9ac1116a7f4e1044ca0ce648daa9db0667794ec1/main.js:9:25151)↵    at Object.e.decode (http://localhost:10240/v/9ac1116a7f4e1044ca0ce648daa9db0667794ec1/main.js:9:24624)↵    at Object.e.decode_object (http://localhost:10240/v/9ac1116a7f4e1044ca0ce648daa9db0667794ec1/main.js:9:24671)↵    at o (http://localhost:10240/v/9ac1116a7f4e1044ca0ce648daa9db0667794ec1/main.js:10:1065)↵    at Object.s [as deserialiseState] (http://localhost:10240/v/9ac1116a7f4e1044ca0ce648daa9db0667794ec1/main.js:10:1151)↵    at HTMLDocument.i (http://localhost:10240/v/9ac1116a7f4e1044ca0ce648daa9db0667794ec1/main.js:36:3046)↵    at u (http://localhost:10240/v/9ac1116a7f4e1044ca0ce648daa9db0667794ec1/main.js:2:9163)↵    at c (http://localhost:10240/v/9ac1116a7f4e1044ca0ce648daa9db0667794ec1/main.js:2:9477)↵    at n (http://localhost:10240/v/9ac1116a7f4e1044ca0ce648daa9db0667794ec1/main.js:6:6904)"
```
when I run locally

**Comment by mattgodbolt** [comment]
Not sure what was going on here, but the last time this happened was two months ago. Closing.
