### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'gapi.client.urlshortener.url')

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#575]
https://sentry.io/matt-godbolt/compiler-explorer/issues/363617379/

```
TypeError: undefined is not an object (evaluating 'gapi.client.urlshortener.url')
  at shortenURL (urlshorten-google.js:47:1)
  at getLinks (sharing.js:137:1)
  at None (sharing.js:101:1)
  at dispatch (ext/jquery/dist/jquery.js:5206:1)
  at trigger (ext/jquery/dist/jquery.js:8201:1)
...
(8 additional frame(s) were not displayed)
```

Seems to be Safari only and maybe linked to https://twitter.com/spun_off/status/918018805028225024?s=09

**Comment by mattgodbolt** [comment]
probably not linked to the Twitter issue after all, but puzzling

**Comment by mattgodbolt** [comment]
This is a duplicate of #272
