### ISSUE TITLE
Builtin list is cached too long

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#584]
https://sentry.io/matt-godbolt/compiler-explorer/issues/368894896/

```
TypeError: Cannot read property 'indexOf' of undefined
  at fromString (vs/editor/file:/Users/penlv/code/vscode/src/vs/editor/common/model/textSource.ts:46:37)
  at fromString (vs/editor/file:/Users/penlv/code/vscode/src/vs/editor/common/model/textSource.ts:138:47)
  at setValue (vs/editor/file:/Users/penlv/code/vscode/src/vs/editor/common/model/textModel.ts:374:33)
  at t.setValue (vs/editor/file:/Users/penlv/code/vscode/src/vs/editor/common/commonCodeEditor.ts:213:15)
  at Editor.<anonymous> (editor.js:257:1)
...
(6 additional frame(s) were not displayed)
```

**Comment by mattgodbolt** [comment]
After a rename seems the results of `builtin/sources/list` was cached... so this more a "why was it cached so long". Probably cloudfront.

**Comment by mattgodbolt** [comment]
Probably worth either replacing the daft builtin thing, or lazily loading it (with less caching).  Just not caching it would slow page loading in general.

**Comment by RabsRincon** [comment]
Do we really need to change this, tho? The renaming was a 1 time thing. I don't think we should change the caching here. Thoughts?

**Comment by mattgodbolt** [comment]
Yeah, this is more a "would be nice to avoid this entirely". Should be a quick fix anyway - if I can't do it in a few minutes when I sit down and give it a go, I'll put this as an enhancement...

**Comment by mattgodbolt** [comment]
Closing, I made the change I wanted to make (mostly), and you're right @RabsRincon !
