### ISSUE TITLE
FPC colourisation issue

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#636]
https://sentry.io/compiler-explorer/compiler-explorer/issues/408602906/

```
Error: fpc: @brackets token returned but no bracket defined as: {

Error: fpc: @brackets token returned but no bracket defined as: {
    at Object.t.throwError (https://fpc.godbolt.org/v/65403cdad9d6a21d8b7929884fb5b8591b86b6b7/ext/monaco-editor/min/vs/editor/editor.main.js:31:583778)
    at e._myTokenize (https://fpc.godbolt.org/v/65403cdad9d6a21d8b7929884fb5b8591b86b6b7/ext/monaco-editor/min/vs/editor/editor.main.js:31:601532)
    at e._tokenize (https://fpc.godbolt.org/v/65403cdad9d6a21d8b7929884fb5b8591b86b6b7/ext/monaco-editor/min/vs/editor/editor.main.js:31:597323)
    at e.tokenize2 (https://fpc.godbolt.org/v/65403cdad9d6a21d8b7929884fb5b8591b86b6b7/ext/monaco-editor/min/vs/editor/editor.main.js:31:597181)
    at t._updateTokensUntilLine (https://fpc.godbolt.org/v/65403cdad9d6a21d8b7929884fb5b8591b86b6b7/ext/monaco-editor/min/vs/editor/editor.main.js:31:801420)
    at https://fpc.godbolt.org/v/65403cdad9d6a21d8b7929884fb5b8591b86b6b7/ext/monaco-editor/min/vs/editor/editor.main.js:31:800989
    at t._withModelTokensChangedEventBuilder (https://fpc.godbolt.org/v/65403cdad9d6a21d8b7929884fb5b8591b86b6b7/ext/monaco-editor/min/vs/editor/editor.main.js:31:798469)
    at t._revalidateTokensNow (https://fpc.godbolt.org/v/65403cdad9d6a21d8b7929884fb5b8591b86b6b7/ext/monaco-editor/min/vs/editor/editor.main.js:31:800718)
    at https://fpc.godbolt.org/v/65403cdad9d6a21d8b7929884fb5b8591b86b6b7/ext/monaco-editor/min/vs/editor/editor.main.js:31:800318
    at n (https://fpc.godbolt.org/v/65403cdad9d6a21d8b7929884fb5b8591b86b6b7/main.js:6:4770)
  at throwError (vs/editor/file:/Users/alex/src/vscode-standalone/src/vs/editor/standalone/common/monarch/monarchCommon.ts:137:8)
  at _myTokenize (vs/editor/file:/Users/alex/src/vscode-standalone/src/vs/editor/standalone/common/monarch/monarchLexer.ts:747:21)
  at _tokenize (vs/editor/file:/Users/alex/src/vscode-standalone/src/vs/editor/standalone/common/monarch/monarchLexer.ts:441:16)
  at tokenize2 (vs/editor/file:/Users/alex/src/vscode-standalone/src/vs/editor/standalone/common/monarch/monarchLexer.ts:433:27)
  at _updateTokensUntilLine (vs/editor/file:/Users/alex/src/vscode-standalone/src/vs/editor/common/model/textModelWithTokens.ts:345:35)
...
(7 additional frame(s) were not displayed)
```

**Comment by mattgodbolt** [comment]
@partouf any thoughts?

**Comment by mattgodbolt** [comment]
https://sentry.io/share/issue/5dcfe272f0374207855f1ff96a22090c/ has more details

**Comment by partouf** [comment]
Ooooh maybe it's the monaco configuration, I was wondering where that error was coming from. Will fix it tonight
