### ISSUE TITLE
Monaco isn't supported on mobile devices

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#641]
https://sentry.io/compiler-explorer/compiler-explorer/issues/375316844/

```
ReferenceError: Map is not defined
  at t._util.t._util (vs/editor/file:/Users/alex/src/vscode-standalone/src/vs/platform/instantiation/common/instantiation.ts:15:32)
  at apply (vs/editor/file:/Users/alex/src/vscode-standalone/src/vs/platform/instantiation/common/instantiation.ts:13:1)
  at execCb (//v/4fff87f34119b45bc2c127533048b2d48dca7df2/ext/requirejs/require.js:1696:33)
  at check (//v/4fff87f34119b45bc2c127533048b2d48dca7df2/ext/requirejs/require.js:883:51)
  at enable (//v/4fff87f34119b45bc2c127533048b2d48dca7df2/ext/requirejs/require.js:1176:22)
...
(30 additional frame(s) were not displayed)
```

**Comment by partouf** [comment]
It seems Map is a Typescript/ES6 thing, it was introduced in January into the Monaco repo https://github.com/Microsoft/vscode/commit/32d16d301f79b0464cbd3fc1c495c7987e8877ad#diff-9dc43a9186b1736753f7d86e93352ea2R14

On the iphone in safari, I seem to have no Monaco issues going on (highlighting and parsing seems fine).

So the question is, which mobile device is used here?

(though I do have massive zooming issues when I click in the editor, but I assume that's not related to this particular issue)

**Comment by RabsRincon** [comment]
Note that Microsoft acknowledges this. From Monaco's ReadMe:
> ❓ Is the editor supported in mobile browsers or mobile web app frameworks?
No.

**Comment by RabsRincon** [comment]
I'll close this one if favour of the linked issue
