### ISSUE TITLE
Handle socket hang up errors

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#70]
Mar 02 05:20:06 8f8106af173b gcc:  Error: socket hang up 
Mar 02 05:20:08 8f8106af173b gcc:      at createHangUpError (http.js:1476:15) 
Mar 02 05:20:25 8f8106af173b gcc:      at Socket.socketCloseListener (http.js:1526:23) 

seems like http://stackoverflow.com/questions/21957258/socket-hang-up-error-with-multiple-http-get-requests may be the answer

**Comment by mattgodbolt** [comment]
Still happening, extremely rarely.

**Comment by mattgodbolt** [comment]
Not seen this for a long while now...closing.
