### ISSUE TITLE
ANSI colour handling error

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#715]
https://sentry.io/compiler-explorer/compiler-explorer/issues/426574778/

```
TypeError: Object doesn't support property or method 'assign'
  at y (ansi-to-html.js:479:1)
  at e (output.js:35:1)
  at subs (output.js:68:1)
  at this (ext/golden-layout/dist/goldenlayout.js:255:1)
  at this (hub.js:194:1)
...
(18 additional frame(s) were not displayed)
```

**Comment by mattgodbolt** [comment]
According to Sentry, error is on:

```
        if (options.colors) {
-->         options.colors = Object.assign({}, defaults.colors, options.colors);
        }
```
