### ISSUE TITLE
Seeing lots of ENOENT errors 

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#761]
Jan 08 14:40:04 bcbcca9b180f unified: error: Error during compilation Error: spawn /compiler-explorer/c-preload/compiler-wrapper ENOENT 
Jan 08 14:40:04 bcbcca9b180f unified:     at _errnoException (util.js:1024:11) 
Jan 08 14:40:04 bcbcca9b180f unified:     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19) 
Jan 08 14:40:04 bcbcca9b180f unified:     at onErrorNT (internal/child_process.js:372:16) 
Jan 08 14:40:04 bcbcca9b180f unified:     at _combinedTickCallback (internal/process/next_tick.js:138:11) 
Jan 08 14:40:04 bcbcca9b180f unified:     at process._tickDomainCallback (internal/process/next_tick.js:218:9)

**Comment by cjdb** [comment]
Is this for MSVC, or something else? Just came to talk about this for all three MSVC compilers.

**Comment by mattgodbolt** [comment]
it seems to be just MSVC. We had to work around some weird directory issues in  24c9bd7d8cd37a70c96aa72b7a33e0f61692a7f4 (not sure why it was suddenly needed), and now we have this issue. I think a step back needs to be taken to work out why we needed the workaround and why this is happneing. I suspect they're related though I'm not 100% sure.

**Comment by AndrewPardoe** [comment]
Note that currently there is no output being produced for MSVC compilers.

**Comment by mattgodbolt** [comment]
Fixed by ace5ee63ad336336d08c639a7c5aa5acd2dc024f - thanks @partouf

**Comment by satya-das** [comment]
I am getting these errors on Ubuntu 16.04 with nodejs 8.9.4 (and also 8.0.0):

```
$ make
Haskell language support disabled
D language support disabled
Rust language support disabled
dirname: missing operand
Try 'dirname --help' for more information.
/home/dassat/github/compiler-explorer/node_modules/.bin/yarn install
yarn install v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.49s.
node_modules/webpack/bin/webpack.js 
Child
    Hash: 6fed961c68f32a9ebaee
    Version: webpack 3.10.0
    Time: 889ms
                                                      Asset       Size  Chunks             Chunk Names
                                    .site-logo.svg.ignoreme    2.59 kB       0  [emitted]  site-logo.svg
                clippy.003c06521ab581ab3f15d16a10627d0d.svg  520 bytes          [emitted]  
    Google-Groups-20px.68f30c7dbd8e0235cf1c52bb2ae11736.png    1.18 kB          [emitted]  
          patreon_logo.b3992c62cc04cc8edb3e513a6da84cb3.png  987 bytes          [emitted]  
        site-logo-beta.155884bf9fbddf60d80ee9e4740609eb.svg    6.15 kB          [emitted]  
     site-logo-inverse.40cafd660c406e77e4971bfb68196684.svg    10.3 kB          [emitted]  
             site-logo.3f5bcf90b56ade7be40ffa8cca8b2056.svg    10.1 kB          [emitted]  
      GitHub-Mark-20px.5baab2d4072294ab236e0886ba739273.png  658 bytes          [emitted]  
                            .site-logo-inverse.svg.ignoreme     2.6 kB       1  [emitted]  site-logo-inverse.svg
                               .site-logo-beta.svg.ignoreme    2.59 kB       2  [emitted]  site-logo-beta.svg
                                 .patreon_logo.png.ignoreme    2.59 kB       3  [emitted]  patreon_logo.png
                                       .clippy.svg.ignoreme    2.58 kB       4  [emitted]  clippy.svg
                           .Google-Groups-20px.png.ignoreme     2.6 kB       5  [emitted]  Google-Groups-20px.png
                             .GitHub-Mark-20px.png.ignoreme     2.6 kB       6  [emitted]  GitHub-Mark-20px.png
                                              manifest.json  986 bytes          [emitted]  
       [0] ./static/assets/clippy.svg 89 bytes {4} [built]
       [1] ./static/assets/GitHub-Mark-20px.png 99 bytes {6} [built]
       [2] ./static/assets/Google-Groups-20px.png 101 bytes {5} [built]
       [3] ./static/assets/patreon_logo.png 95 bytes {3} [built]
       [4] ./static/assets/site-logo-beta.svg 97 bytes {2} [built]
       [5] ./static/assets/site-logo-inverse.svg 100 bytes {1} [built]
       [6] ./static/assets/site-logo.svg 92 bytes {0} [built]
make -C c-preload
make[1]: Entering directory '/home/dassat/github/compiler-explorer/c-preload'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/dassat/github/compiler-explorer/c-preload'
./node_modules/.bin/supervisor -w app.js,lib,etc/config -e 'js|node|properties' --exec   -- ./app.js 

Running node-supervisor with
  program './app.js'
  --watch 'app.js,lib,etc/config'
  --extensions 'js|node|properties'
  --exec '--'

Starting child process with '-- ./app.js'
Watching directory '/home/dassat/github/compiler-explorer/app.js' for changes.
Press rs for restarting the process.
Watching directory '/home/dassat/github/compiler-explorer/lib' for changes.
Press rs for restarting the process.
Watching directory '/home/dassat/github/compiler-explorer/etc/config' for changes.
Press rs for restarting the process.
Parent process exiting, terminating child...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn -- ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Makefile:94: recipe for target 'run' failed
make: *** [run] Error 1
```

**Comment by jaredwy** [comment]
That looks like a very different stack. Would you be able to open a seperate bug so we can track it?

**Comment by satya-das** [comment]
Sure. I just opened https://github.com/mattgodbolt/compiler-explorer/issues/850.
Thanks
