### ISSUE TITLE
ENOENT occurs on Ubuntu 16.04

### ISSUE THREAD

**Issue by satya-das** [mattgodbolt/compiler-explorer#850]
I am getting following error on Ubuntu 16.04 with nodejs 8.9.4 (and also 8.0.0). When I tried it on OSX it worked flawlessly.
Error that I get on ubuntu:
```
$ make
Haskell language support disabled
D language support disabled
Rust language support disabled
dirname: missing operand
Try 'dirname --help' for more information.
/home/dassat/github/compiler-explorer/node_modules/.bin/yarn install
yarn install v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.49s.
node_modules/webpack/bin/webpack.js 
Child
    Hash: 6fed961c68f32a9ebaee
    Version: webpack 3.10.0
    Time: 889ms
                                                      Asset       Size  Chunks             Chunk Names
                                    .site-logo.svg.ignoreme    2.59 kB       0  [emitted]  site-logo.svg
                clippy.003c06521ab581ab3f15d16a10627d0d.svg  520 bytes          [emitted]  
    Google-Groups-20px.68f30c7dbd8e0235cf1c52bb2ae11736.png    1.18 kB          [emitted]  
          patreon_logo.b3992c62cc04cc8edb3e513a6da84cb3.png  987 bytes          [emitted]  
        site-logo-beta.155884bf9fbddf60d80ee9e4740609eb.svg    6.15 kB          [emitted]  
     site-logo-inverse.40cafd660c406e77e4971bfb68196684.svg    10.3 kB          [emitted]  
             site-logo.3f5bcf90b56ade7be40ffa8cca8b2056.svg    10.1 kB          [emitted]  
      GitHub-Mark-20px.5baab2d4072294ab236e0886ba739273.png  658 bytes          [emitted]  
                            .site-logo-inverse.svg.ignoreme     2.6 kB       1  [emitted]  site-logo-inverse.svg
                               .site-logo-beta.svg.ignoreme    2.59 kB       2  [emitted]  site-logo-beta.svg
                                 .patreon_logo.png.ignoreme    2.59 kB       3  [emitted]  patreon_logo.png
                                       .clippy.svg.ignoreme    2.58 kB       4  [emitted]  clippy.svg
                           .Google-Groups-20px.png.ignoreme     2.6 kB       5  [emitted]  Google-Groups-20px.png
                             .GitHub-Mark-20px.png.ignoreme     2.6 kB       6  [emitted]  GitHub-Mark-20px.png
                                              manifest.json  986 bytes          [emitted]  
       [0] ./static/assets/clippy.svg 89 bytes {4} [built]
       [1] ./static/assets/GitHub-Mark-20px.png 99 bytes {6} [built]
       [2] ./static/assets/Google-Groups-20px.png 101 bytes {5} [built]
       [3] ./static/assets/patreon_logo.png 95 bytes {3} [built]
       [4] ./static/assets/site-logo-beta.svg 97 bytes {2} [built]
       [5] ./static/assets/site-logo-inverse.svg 100 bytes {1} [built]
       [6] ./static/assets/site-logo.svg 92 bytes {0} [built]
make -C c-preload
make[1]: Entering directory '/home/dassat/github/compiler-explorer/c-preload'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/dassat/github/compiler-explorer/c-preload'
./node_modules/.bin/supervisor -w app.js,lib,etc/config -e 'js|node|properties' --exec   -- ./app.js 

Running node-supervisor with
  program './app.js'
  --watch 'app.js,lib,etc/config'
  --extensions 'js|node|properties'
  --exec '--'

Starting child process with '-- ./app.js'
Watching directory '/home/dassat/github/compiler-explorer/app.js' for changes.
Press rs for restarting the process.
Watching directory '/home/dassat/github/compiler-explorer/lib' for changes.
Press rs for restarting the process.
Watching directory '/home/dassat/github/compiler-explorer/etc/config' for changes.
Press rs for restarting the process.
Parent process exiting, terminating child...
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn -- ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:686:11)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
Makefile:94: recipe for target 'run' failed
make: *** [run] Error 1
```

**Comment by mattgodbolt** [comment]
Hi @satya-das -- does this error happen immediately on start-up?

**Comment by satya-das** [comment]
Hi @mattgodbolt , yes it happens immediately. I didn't even open the browser. I tried multiple times and I got same error.
I had seen this problem with my office computer and now I thought let's try with Virtual Box on my personal computer and it worked. I did get some warnings but no exception and am able to see disassembly in the browser.
But my guess is that it might not be machine dependent.
Please let me know if any more info is needed or I can be of any help.

**Comment by mattgodbolt** [comment]
Can you try `make debug`  and copy here what it says, then `make EXTRA_FLAGS="--debug"`
 and see if any clues come from that? (And we'll combine these into one step shortly!)

Thanks!

**Comment by satya-das** [comment]
Hi @mattgodbolt , below is the verbatim copy-paste of outputs of your suggested commands:
```
[21:20:40] dassat:~/github/compiler-explorer$ make debug
dirname: missing operand
Try 'dirname --help' for more information.
Using node from
Using yarn from /home/dassat/github/compiler-explorer/node_modules/.bin/yarn
PATH is :/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Tools/3rdParty/Common/gradle/gradle-1.11/bin:/home/dassat/Tools/android/android-sdk-linux/platform-tools:/home/dassat/Tools/android/android-sdk-linux/tools:/home/dassat/Tools/android/android-sdk-linux/build-tools/23.0.1/:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/ndk9c/tool:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Utils/apktool:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Utils/graphviz/bin:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Utils/Doxygen:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/TomTom/ttimage/dist:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Utils/png2rle/dist:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Utils/e2fstools/dist:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Build/ant/bin:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/sdk24/tools:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/sdk24/platform-tools:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/ndk9c:/usr/java/jdk1.8.0_112//bin:/usr/java/jdk1.8.0_112/::/home/dassat/bin:/home/dassat/.local/bin:/home/dassat/bin/p4v/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/ndk9c:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/sdk24/platform-tools:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/sdk24/tools:/home/dassat/Programs/nodejs/node-v8.0.0-linux-x64/bin:/home/dassat/local/bin
[21:20:45] dassat:~/github/compiler-explorer$ make EXTRA_FLAGS="--debug"
Haskell language support disabled
D language support disabled
Rust language support disabled
dirname: missing operand
Try 'dirname --help' for more information.
/home/dassat/github/compiler-explorer/node_modules/.bin/yarn install
yarn install v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.56s.
node_modules/webpack/bin/webpack.js 
Child
    Hash: 6fed961c68f32a9ebaee
    Version: webpack 3.10.0
    Time: 1093ms
                                                      Asset       Size  Chunks             Chunk Names
                                    .site-logo.svg.ignoreme    2.59 kB       0  [emitted]  site-logo.svg
                clippy.003c06521ab581ab3f15d16a10627d0d.svg  520 bytes          [emitted]  
    Google-Groups-20px.68f30c7dbd8e0235cf1c52bb2ae11736.png    1.18 kB          [emitted]  
          patreon_logo.b3992c62cc04cc8edb3e513a6da84cb3.png  987 bytes          [emitted]  
        site-logo-beta.155884bf9fbddf60d80ee9e4740609eb.svg    6.15 kB          [emitted]  
     site-logo-inverse.40cafd660c406e77e4971bfb68196684.svg    10.3 kB          [emitted]  
             site-logo.3f5bcf90b56ade7be40ffa8cca8b2056.svg    10.1 kB          [emitted]  
      GitHub-Mark-20px.5baab2d4072294ab236e0886ba739273.png  658 bytes          [emitted]  
                            .site-logo-inverse.svg.ignoreme     2.6 kB       1  [emitted]  site-logo-inverse.svg
                               .site-logo-beta.svg.ignoreme    2.59 kB       2  [emitted]  site-logo-beta.svg
                                 .patreon_logo.png.ignoreme    2.59 kB       3  [emitted]  patreon_logo.png
                                       .clippy.svg.ignoreme    2.58 kB       4  [emitted]  clippy.svg
                           .Google-Groups-20px.png.ignoreme     2.6 kB       5  [emitted]  Google-Groups-20px.png
                             .GitHub-Mark-20px.png.ignoreme     2.6 kB       6  [emitted]  GitHub-Mark-20px.png
                                              manifest.json  986 bytes          [emitted]  
       [0] ./static/assets/clippy.svg 89 bytes {4} [built]
       [1] ./static/assets/GitHub-Mark-20px.png 99 bytes {6} [built]
       [2] ./static/assets/Google-Groups-20px.png 101 bytes {5} [built]
       [3] ./static/assets/patreon_logo.png 95 bytes {3} [built]
       [4] ./static/assets/site-logo-beta.svg 97 bytes {2} [built]
       [5] ./static/assets/site-logo-inverse.svg 100 bytes {1} [built]
       [6] ./static/assets/site-logo.svg 92 bytes {0} [built]
make -C c-preload
make[1]: Entering directory '/home/dassat/github/compiler-explorer/c-preload'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/dassat/github/compiler-explorer/c-preload'
./node_modules/.bin/supervisor -w app.js,lib,etc/config -e 'js|node|properties' --exec   -- ./app.js 

Running node-supervisor with
  program './app.js'
  --watch 'app.js,lib,etc/config'
  --extensions 'js|node|properties'
  --exec '--'

Starting child process with '-- ./app.js'
Watching directory '/home/dassat/github/compiler-explorer/app.js' for changes.
Press rs for restarting the process.
Watching directory '/home/dassat/github/compiler-explorer/lib' for changes.
Press rs for restarting the process.
Watching directory '/home/dassat/github/compiler-explorer/etc/config' for changes.
Press rs for restarting the process.
Parent process exiting, terminating child...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn -- ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
Makefile:94: recipe for target 'run' failed
make: *** [run] Error 1
```

**Comment by mattgodbolt** [comment]
Ahhhhh!  Ok, I'm relying on the 'dirname' command which is not present on
your machine! Whoops!

I am away from a computer but if you can install 'dirname' it will probably
start working. Well fix this up on our side though too!

**Comment by satya-das** [comment]
dirname program is there:
```
[10:28:30] dassat:~$ which dirname
/usr/bin/dirname
```
The error says:
```
[10:28:43] dassat:~/github/compiler-explorer$ make EXTRA_FLAGS="--debug"
Haskell language support disabled
D language support disabled
Rust language support disabled
dirname: missing operand
Try 'dirname --help' for more information
...
```
So, it is about missing operand in dirname and not the missing program itself.

**Comment by satya-das** [comment]
Hi @mattgodbolt, I analyzed this error and solved it. The problem was that there was an existing *.node-bin* file that was empty. When I removed it the problem was solved. Maybe this file was created because I had a non-compatible node prior to running make for the very first time. I had removed that when compiler-explorer complained about it. Maybe the .node-bin file was created in that very run of make which was left empty and the subsequent one did not create it because it was already there.

RESOLUTION
===========
If there is an empty (or faulty) .node-bin then this problem happens.

**Comment by satya-das** [comment]
Hi @mattgodbolt , below is the verbatim copy-paste of outputs of your suggested commands:
```
[21:20:40] dassat:~/github/compiler-explorer$ make debug
dirname: missing operand
Try 'dirname --help' for more information.
Using node from
Using yarn from /home/dassat/github/compiler-explorer/node_modules/.bin/yarn
PATH is :/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Tools/3rdParty/Common/gradle/gradle-1.11/bin:/home/dassat/Tools/android/android-sdk-linux/platform-tools:/home/dassat/Tools/android/android-sdk-linux/tools:/home/dassat/Tools/android/android-sdk-linux/build-tools/23.0.1/:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/ndk9c/tool:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Utils/apktool:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Utils/graphviz/bin:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Utils/Doxygen:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/TomTom/ttimage/dist:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Utils/png2rle/dist:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Utils/e2fstools/dist:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Build/ant/bin:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/sdk24/tools:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/sdk24/platform-tools:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/ndk9c:/usr/java/jdk1.8.0_112//bin:/usr/java/jdk1.8.0_112/::/home/dassat/bin:/home/dassat/.local/bin:/home/dassat/bin/p4v/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/ndk9c:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/sdk24/platform-tools:/home/dassat/Perforce/dassat_ubuntu16_devenv/ct/devenv/main/Linux/Android/sdk24/tools:/home/dassat/Programs/nodejs/node-v8.0.0-linux-x64/bin:/home/dassat/local/bin
[21:20:45] dassat:~/github/compiler-explorer$ make EXTRA_FLAGS="--debug"
Haskell language support disabled
D language support disabled
Rust language support disabled
dirname: missing operand
Try 'dirname --help' for more information.
/home/dassat/github/compiler-explorer/node_modules/.bin/yarn install
yarn install v1.5.1
[1/5] Validating package.json...
[2/5] Resolving packages...
success Already up-to-date.
Done in 0.56s.
node_modules/webpack/bin/webpack.js 
Child
    Hash: 6fed961c68f32a9ebaee
    Version: webpack 3.10.0
    Time: 1093ms
                                                      Asset       Size  Chunks             Chunk Names
                                    .site-logo.svg.ignoreme    2.59 kB       0  [emitted]  site-logo.svg
                clippy.003c06521ab581ab3f15d16a10627d0d.svg  520 bytes          [emitted]  
    Google-Groups-20px.68f30c7dbd8e0235cf1c52bb2ae11736.png    1.18 kB          [emitted]  
          patreon_logo.b3992c62cc04cc8edb3e513a6da84cb3.png  987 bytes          [emitted]  
        site-logo-beta.155884bf9fbddf60d80ee9e4740609eb.svg    6.15 kB          [emitted]  
     site-logo-inverse.40cafd660c406e77e4971bfb68196684.svg    10.3 kB          [emitted]  
             site-logo.3f5bcf90b56ade7be40ffa8cca8b2056.svg    10.1 kB          [emitted]  
      GitHub-Mark-20px.5baab2d4072294ab236e0886ba739273.png  658 bytes          [emitted]  
                            .site-logo-inverse.svg.ignoreme     2.6 kB       1  [emitted]  site-logo-inverse.svg
                               .site-logo-beta.svg.ignoreme    2.59 kB       2  [emitted]  site-logo-beta.svg
                                 .patreon_logo.png.ignoreme    2.59 kB       3  [emitted]  patreon_logo.png
                                       .clippy.svg.ignoreme    2.58 kB       4  [emitted]  clippy.svg
                           .Google-Groups-20px.png.ignoreme     2.6 kB       5  [emitted]  Google-Groups-20px.png
                             .GitHub-Mark-20px.png.ignoreme     2.6 kB       6  [emitted]  GitHub-Mark-20px.png
                                              manifest.json  986 bytes          [emitted]  
       [0] ./static/assets/clippy.svg 89 bytes {4} [built]
       [1] ./static/assets/GitHub-Mark-20px.png 99 bytes {6} [built]
       [2] ./static/assets/Google-Groups-20px.png 101 bytes {5} [built]
       [3] ./static/assets/patreon_logo.png 95 bytes {3} [built]
       [4] ./static/assets/site-logo-beta.svg 97 bytes {2} [built]
       [5] ./static/assets/site-logo-inverse.svg 100 bytes {1} [built]
       [6] ./static/assets/site-logo.svg 92 bytes {0} [built]
make -C c-preload
make[1]: Entering directory '/home/dassat/github/compiler-explorer/c-preload'
make[1]: Nothing to be done for 'all'.
make[1]: Leaving directory '/home/dassat/github/compiler-explorer/c-preload'
./node_modules/.bin/supervisor -w app.js,lib,etc/config -e 'js|node|properties' --exec   -- ./app.js 

Running node-supervisor with
  program './app.js'
  --watch 'app.js,lib,etc/config'
  --extensions 'js|node|properties'
  --exec '--'

Starting child process with '-- ./app.js'
Watching directory '/home/dassat/github/compiler-explorer/app.js' for changes.
Press rs for restarting the process.
Watching directory '/home/dassat/github/compiler-explorer/lib' for changes.
Press rs for restarting the process.
Watching directory '/home/dassat/github/compiler-explorer/etc/config' for changes.
Press rs for restarting the process.
Parent process exiting, terminating child...
events.js:182
      throw er; // Unhandled 'error' event
      ^

Error: spawn -- ENOENT
    at exports._errnoException (util.js:1026:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:189:19)
    at onErrorNT (internal/child_process.js:366:16)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)
    at Function.Module.runMain (module.js:607:11)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:575:3
Makefile:94: recipe for target 'run' failed
make: *** [run] Error 1
```

**Comment by mattgodbolt** [comment]
Thanks so much for finding the root issue @satya-das ! We will try and find a better way of solving this (or detecting it at lesat!!)

**Comment by satya-das** [comment]
@mattgodbolt, my pleasure. :).
And thank you for addressing it immediately.

**Comment by mattgodbolt** [comment]
Going to close this: I think my solution is "good enough" for now. Feel free to reopen if not.

**Comment by PinkyJ12** [comment]
I am getting same issue,I tried multiple times and I got same error.And can't figure out which .node-bin file is empty. please help.
