### ISSUE TITLE
Cfg view: attempt to create duplicate IDs

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/compiler-explorer#926]
https://sentry.io/compiler-explorer/compiler-explorer/issues/553051839/

```
Error: Cannot add item: item with id  push rbp already exists
  at this (./static/cfg-view.js:326:1)
  at jQuery (./static/cfg-view.js:114:1)
...
(17 additional frame(s) were not displayed)
```

**Comment by mattgodbolt** [comment]
@cppchedy if you have a moment perhaps you could see if you know what this might be?

**Comment by mattgodbolt** [comment]
Seems fixed: no instances of this happening in the last 90 days.
