### ISSUE TITLE
Rust compiling error "could not copy"

### ISSUE THREAD

**Issue by TheIronBorn** [mattgodbolt/compiler-explorer#942]
```
error: could not copy "/tmp/compiler-explorer-compiler118431-63-tlvmtc.cd56o/output.example0.rcgu.s" to "/tmp/compiler-explorer-compiler118431-63-tlvmtc.cd56o/output.s": Operation not permitted (os error 1)
error: aborting due to previous error
Compiler returned: 101
```

### found on https://godbolt.org/g/sjtE1B

Firefox: 61.0b9
Godbolt: 7707a2f (copied from most recent "Changelog" entry)
rustc: `1.28.0-nightly (5d0631a64 2018-05-30)` (per the Godbolt compiler info)

**Comment by mattgodbolt** [comment]
This seems only to be on the nightly build: https://godbolt.org/g/rBepxV is a minimal example.

**Comment by mattgodbolt** [comment]
Running the code directly (on the management node) works:

```
$ /opt/compiler-explorer/rust-nightly/bin/rustc --emit asm test.rs --crate-type rlib
```

So I suspect the `LD_PRELOAD` trickery is upsetting rust.

**Comment by mattgodbolt** [comment]
Couldn't reproduce with the `LD_PRELOAD`, but if I run the compiler inside the `docker` container:

```
sudo docker exec -ti unified /bin/bash
gcc-user@c45dac5bb5c7:/compiler-explorer$ cd /tmp
gcc-user@c45dac5bb5c7:/tmp$ cat > test.rs
// Type your code here, or load an example.
pub fn square(num: i32) -> i32 {
    num * num
}
gcc-user@c45dac5bb5c7:/tmp$ /opt/compiler-explorer/rust-nightly/bin/rustc -C debuginfo=1 -o /tmp/moose.s --emit asm test.rs --crate-type rlib
error: could not copy "/tmp/moose.test0.rcgu.s" to "/tmp/moose.s": Operation not permitted (os error 1)

error: aborting due to previous error
```

...we get to see the error...

**Comment by nicokoch** [comment]
PR opened: https://github.com/rust-lang/rust/pull/51270/

**Comment by mattgodbolt** [comment]
Ok I worked out how to strace... and the mystery deepens: I've filed a bug against `rustc`

**Comment by mattgodbolt** [comment]
A new docker fixes the issue.

**Comment by TheIronBorn** [comment]
Just me or did it break again? https://godbolt.org/g/MtYiCK
```
/compiler-explorer/c-preload/compiler-wrapper: line 21: 15060 Segmentation fault      (core dumped) "$@"
Compiler returned: 139

**Comment by gamozolabs** [comment]
Yeah, it was working for a while yesterday but now I'm getting the same segfault issue.

**Comment by mattgodbolt** [comment]
Oh, hmm! that's weird.

As part of updating docker and whatnot I have also moved to Ubuntu 18.04 across the board. I wonder if that's something to do with it. Will investigate.

**Comment by mattgodbolt** [comment]
...or unless the new nightly now segfaults under the situations where previously it had worked...

**Comment by mattgodbolt** [comment]
I can reproduce. Will update the rust bug...

**Comment by mattgodbolt** [comment]
Ok, it's not docker any more: just seems the nightly rust is crashing at startup - this is from the host (not in a container):

```
ubuntu@ip-172-30-2-197:~$ gdb --args /opt/compiler-explorer/rust-nightly/bin/rustc -C debuginfo=1 -o /tmp/moose.s --emit asm test.rs --crate-type rlib
GNU gdb (Ubuntu 8.1-0ubuntu3) 8.1.0.20180409-git
Copyright (C) 2018 Free Software Foundation, Inc. 
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /opt/compiler-explorer/rust-nightly/bin/rustc...(no debugging symbols found)...done.
(gdb) r
Starting program: /opt/compiler-explorer/rust-nightly/bin/rustc -C debuginfo=1 -o /tmp/moose.s --emit asm test.rs --crate-type rlib
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Error while mapping shared library sections:
`/opt/compiler-explorer/rust-nightly/lib/rustlib/x86_64-unknown-linux-gnu/codegen-backends/librustc_codegen_llvm-llvm.so': not in executable format: File format not recognized

Program received signal SIGSEGV, Segmentation fault.
0x00007fffecd6d24a in ?? ()
(gdb) bt
#0  0x00007fffecd6d24a in ?? ()
#1  0x0000000000000000 in ?? ()
```

- I `strip` executables; I suspect that's now breaking. Will disable it and see.

**Comment by mattgodbolt** [comment]
That seems to be it....

**Comment by mattgodbolt** [comment]
All should be well now! Thanks for your patience.
